project:
  type: website

website:
  title: "Communication Science R Book"
  sidebar:
    style: "docked"
    search: true
    contents:
      - "pages/getting-started.qmd"
      - section: "Overview of functions"
        href: "pages/functions/0-index.qmd"
        contents:
          - section: "Data management"
            href: "pages/functions/data_management/0-index.qmd"
            contents:
              - "pages/functions/data_management/select.qmd"
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


execute:
  freeze: auto
