project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!*WIP*"

website:
  title: "Communication Science R Book"
  sidebar:
    title: "Communication Science R Book"
    allignment: center
    logo: "data/logo.png"
    logo-href: "https://vu.nl/en/about-vu/faculties/faculty-of-social-sciences/departments/communication-science"
    search: true
    style: "docked"
    collapse-level: 1
    contents: auto

  page-footer:
    background: primary
    left: ""
  back-to-top-navigation: true
  page-navigation: true

bibliography: references/references.bib
cls: references/apa7.cls

format:
  html:
    theme:
      - cerulean
      - style.scss
    toc: true

execute:
  freeze: auto

resources:
  - "data/"