project:
  type: website

website:
  title: "Communication Science R Book"
  sidebar:
    style: "docked"
    search: true
    contents: auto
    
format:
  html:
    theme: 
      - cosmo
      - style.scss
    toc: true


execute:
  freeze: auto
