---
title: Files and projects
subtitle: Reading and writing files, and the convenience of projects
---


# A quick introduction to your file system {#filesystem}

When working in R, you will often need to read and save files on your computer.
Moreover, when you work with sensive data, such as survey responses, you really need to understand where your data is stored and how to access it.
Here we provide a basic introduction to the file system on your computer.

Computers organize files and directories (or folders) in a hierarchical structure that resembles a tree. 
This tree-like structure starts from a single **root directory** and branches out into subdirectories, which can contain more subdirectories or files.
On windows the root directory is often `C:\`, while on macOS and Linux it's simply `/`. Also
It kind of looks like this:

```{r, eval=FALSE}
/ (Root Directory) 
│
├── Documents
│   ├── Work
│   │   ├── survey.csv
│   │   └──  
│   └── Personal
│       ├── Resume.pdf
│       └── Budget.xlsx
│
├── Downloads
│   ├── Report.docx
│   └── image.jpg
```

Because of this structure, any file on your computer has a unique **path** that describes its location in the file system.
For example, the path to the `Report.docx` file in the `Work` directory would be `/Documents/Work/survey.csv` (or `C:\Documents\Work\survey.csv` on Windows). 
In reality there are more layers, such as your user directory, but you get the gist.

To write or read a file in R, you can specify the file path in two ways: using an **absolute path** (starting from the root directory) or a **relative path** (starting from the current working directory).

## Absolute path

An absolute path specifies the full path to a file or directory from the root directory.
There are several ways to find out the absolute path of a file on your computer:

- **From the file explorer**: Open the file explorer on your computer, and navigate to the file. You can then right-click on the file and select *Properties* (or some similar term). Here you'll find the *Location* of the file. **Even easier**: you can right-click on the file and copy it, and when you then paste it into RStudio, it will paste the file path.
- **Using file.choose()**: If you run the code `file.choose()`, R will open a file explorer window. Here you can browse to the file, and when you select it, R will print the file path in the console window.
- **Using RStudio**: For some types of files, you can use the RStudio *data importer* interface. In the bottom-right window, you can go to the `Files` tab. Here you can browse to the file on your computer. If the file is something that you can read into R (e.g., a CSV file), RStudio will give you the `Import Dataset` option. This will open a visual interface for importing the data, that also shows the file path.


## Relative path

Whenever you are working in R, you are always working in a specific directory on your computer. 
This directory is called the **working directory**.
You can check the current working directory with the `getwd()` function:
This prints the current working directory in your console. 

For example, say that our current working directory is `/Documents/Work` (in the example file system above).
This allows us to access the `survey.csv` file with a relative path: `survey.csv`.
Also, if we would now create a new file in R called `my_analysis.r`, it would be saved as `/Documents/Work/my_analysis.r`.

In other words, by setting our working directory, we can avoid having to write out the full path to a file every time we want to read or write.
There are two easy ways to set the working directory in R:

* **Manually**: You can set the working directory with the `setwd()` function. For example, to set the working directory to `/Documents/Work`, you can run `setwd("/Documents/Work")`.
* **Using RStudio**: In RStudio, you can set the working directory by clicking on `Session` in the menu bar, then `Set Working Directory`, and then `Choose Directory`. This will open a file explorer window where you can select the directory you want to set as the working directory.


# Projects

Setting your working directory can be a good way to manage files on your on computer.
However, if you are working on a project, it can be even more convenient to start an actual **project** in RStudio.

In the top-right corner of your RStudio window, you can see a button labeled **Project: (None)**.
If you click it, you can create a new project. 
You can create this project in a new or existing directory on your computer.
This will mark the directory as a project, and in the top-right corner you will see the name of the project instead of **Project: (None)**.

Projects are very convenient because they allow you to store all your files and data for a project in a single directory.
The working directory is automatically set to the project directory, and you can easily access all files in the project from the RStudio interface.
Moreover, if you share the project with others, they can easily open the project in RStudio and start working on it.
As long as you make sure to save all files in the project directory, and use relative paths to access files, your code will work on any computer.
