{
  "hash": "e2ec6369e9f3c375cfca313f0475ede8",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: t-test\nsummary: Comparing two means\nformat:\n  html:\n    df-print: paged\norder: 1\n---\n\n\n\n\n\n# What is a t-test?\n\nA t-test is a statistical test used to determine if there is a significant difference between two means. \nIt is comparable to the z-test, but is more appropriate when the sample size is small or the population standard deviation is unknown.\nWhere the z-test is based on the z-=istribution (i.e. the normal distribution), the t-test is based on the t-distribution, which takes into account the uncertainty in the estimate of the population standard deviation.\nIf the sample size is small, the t-distribution has heavier tails than the z-distribution, which makes it less likely to make a Type I error (i.e., rejecting the null hypothesis when it is true).\n\nIn the following plot we show the normal (z) and t-distributions for two different sample sizes: 5 and 30.\nYou see that in the left plot, with a sample size of 5, the t-distribution has heavier tails than the normal distribution, and so the critical values (p-value thresholds) are further apart.\nAs the sample size increases, the t-distribution approaches the normal distribution, and the critical values converge.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](t-test_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n\n\nIn practice, the t-test is generally preferred when the population standard deviation is unknown (even if the sample size is large).\nThere are three main types of t-tests: the one-sample t-test, the independent samples t-test, and the paired samples t-test.[^other_uses]\n\n[^other_uses]:\nYou may also encounter the t-distribution in other contexts, such as for testing the significance of individual coefficients in a regression model (i.e. is the coefficient significantly different from zero?).\nIn this tutorial we focus on the t-test as a standalone statistical test, but the t-distribution has many other uses in statistics.\n\n### One-sample t-test\n  * **Purpose**. Compare the mean of a single sample to a known value (e.g., a population mean).\n  * **Example**. You have a sample of students and you want to test if the average time they spend on social media is significantly different from the national average (which we would then need to know in advance).\n  \n### Independent samples t-test\n  * **Purpose**. Compare the means *between* two independent groups. \n  * **Example**. You conducted an experiment where you randomly assign participants to play either a *violent* or *non-violent* video game, and you want to test if the hearth rate in the *violent* group is significantly higher than in the *non-violent* group after playing the game.\n\n### Paired samples t-test\n  * **Purpose**. Compare the means *within subjects* (e.g., within a person) at two different time points or under two different conditions. In this case the samples are not independent, because the two observations are *paired*.\n  * **Example**. You measured the hearth rate of the same participants before and after playing a video game, and you want to test if there is a significant increase.\n\n\n# How to use \n\nThe t-test is included in base R, but we'll also need the `car` package for the Levene's test (as you'll see later).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(car)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: carData\n```\n\n\n:::\n:::\n\n\n\n\nFor the examples we'll use our [practice dataset](../../data-management/index.qmd#practice-data). \nWe'll use the following variables:\n\n* **news_consumption**. A continuous variable measuring the number of hours per week that a person spends consuming news.\n* **np_subscription**. A binary variable indicating whether the person has a subscription to a national newspaper (1 = yes, 0 = no).\n* **experiment_group**. A categorical variable indicating the group to which the participant was assigned in an experiment. Each group viewed a different movie that was either *neutral*, *positive*, or *negative* about journalism.\n* **trust_t1 & trust_t2**. Two continuous variables measuring a participant's trust in journalism before and after the experiment.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\nd <- read_csv(\"https://tinyurl.com/R-practice-data\") |>\n        select(news_consumption = `news consumption`,\n               np_subscription, \n               experiment_group, \n               trust_t1, \n               trust_t2)\nd\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"news_consumption\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"np_subscription\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"experiment_group\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"trust_t1\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"trust_t2\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"17\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"3.00\",\"5\":\"2.824978\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"5.00\",\"5\":\"5.354581\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"3.25\",\"5\":\"3.368898\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"4.25\",\"5\":\"2.882763\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"4.00\",\"5\":\"3.256695\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"3.75\",\"5\":\"6.460656\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"3.75\",\"5\":\"6.380898\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"2.75\",\"5\":\"4.833257\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.25\",\"5\":\"6.817680\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"5.75\",\"5\":\"6.227435\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"3.00\",\"5\":\"4.625826\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.50\",\"5\":\"3.749982\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.25\",\"5\":\"5.668970\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.25\",\"5\":\"4.595916\"},{\"1\":\"10\",\"2\":\"no\",\"3\":\"control\",\"4\":\"4.00\",\"5\":\"4.693604\"},{\"1\":\"16\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"3.25\",\"5\":\"4.626647\"},{\"1\":\"9\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"4.00\",\"5\":\"3.515036\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"control\",\"4\":\"5.75\",\"5\":\"7.857036\"},{\"1\":\"11\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.00\",\"5\":\"5.065938\"},{\"1\":\"13\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"3.75\",\"5\":\"2.966268\"},{\"1\":\"15\",\"2\":\"no\",\"3\":\"control\",\"4\":\"3.50\",\"5\":\"3.031485\"},{\"1\":\"16\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"5.50\",\"5\":\"6.313042\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.75\",\"5\":\"6.178895\"},{\"1\":\"15\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"4.75\",\"5\":\"4.289748\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"3.50\",\"5\":\"7.303969\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"5.00\",\"5\":\"7.411312\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"5.50\",\"5\":\"6.497374\"},{\"1\":\"13\",\"2\":\"no\",\"3\":\"control\",\"4\":\"4.00\",\"5\":\"5.721720\"},{\"1\":\"10\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"5.50\",\"5\":\"6.974339\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"3.50\",\"5\":\"3.349274\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.75\",\"5\":\"7.836750\"},{\"1\":\"8\",\"2\":\"no\",\"3\":\"control\",\"4\":\"3.00\",\"5\":\"3.441744\"},{\"1\":\"10\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"6.25\",\"5\":\"7.719089\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"3.25\",\"5\":\"4.677334\"},{\"1\":\"13\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"3.50\",\"5\":\"4.340828\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"5.50\",\"5\":\"6.739357\"},{\"1\":\"21\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"3.50\",\"5\":\"5.479072\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"5.25\",\"5\":\"5.637100\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"5.00\",\"5\":\"8.944965\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.75\",\"5\":\"5.636468\"},{\"1\":\"8\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"5.50\",\"5\":\"2.115650\"},{\"1\":\"18\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"5.50\",\"5\":\"7.095705\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.25\",\"5\":\"5.696713\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.00\",\"5\":\"4.387470\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"5.25\",\"5\":\"5.775667\"},{\"1\":\"17\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"6.50\",\"5\":\"8.359841\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.00\",\"5\":\"5.993076\"},{\"1\":\"8\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"2.50\",\"5\":\"3.197211\"},{\"1\":\"13\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"2.50\",\"5\":\"2.728577\"},{\"1\":\"10\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"3.75\",\"5\":\"5.340899\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.50\",\"5\":\"8.375465\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"3.75\",\"5\":\"4.147598\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.50\",\"5\":\"5.322031\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"3.75\",\"5\":\"6.284208\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.25\",\"5\":\"6.197204\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"5.25\",\"5\":\"7.424373\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"5.50\",\"5\":\"7.392493\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.50\",\"5\":\"4.476418\"},{\"1\":\"19\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"3.00\",\"5\":\"1.200073\"},{\"1\":\"8\",\"2\":\"no\",\"3\":\"control\",\"4\":\"7.00\",\"5\":\"6.517363\"},{\"1\":\"15\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"3.50\",\"5\":\"6.175327\"},{\"1\":\"16\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"3.75\",\"5\":\"4.231543\"},{\"1\":\"14\",\"2\":\"no\",\"3\":\"control\",\"4\":\"4.25\",\"5\":\"5.444230\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"3.25\",\"5\":\"2.732212\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.50\",\"5\":\"5.876735\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.75\",\"5\":\"6.471384\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.25\",\"5\":\"4.851863\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"3.50\",\"5\":\"3.148748\"},{\"1\":\"13\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.50\",\"5\":\"5.116448\"},{\"1\":\"14\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"3.25\",\"5\":\"3.952229\"},{\"1\":\"9\",\"2\":\"no\",\"3\":\"control\",\"4\":\"4.50\",\"5\":\"4.545750\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"5.25\",\"5\":\"6.432647\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.50\",\"5\":\"6.089041\"},{\"1\":\"17\",\"2\":\"no\",\"3\":\"control\",\"4\":\"1.75\",\"5\":\"1.982712\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"5.50\",\"5\":\"6.999044\"},{\"1\":\"21\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.00\",\"5\":\"4.264509\"},{\"1\":\"13\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"4.00\",\"5\":\"3.120222\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"6.25\",\"5\":\"7.695243\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"4.75\",\"5\":\"4.875016\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"control\",\"4\":\"4.50\",\"5\":\"6.082364\"},{\"1\":\"15\",\"2\":\"no\",\"3\":\"control\",\"4\":\"3.25\",\"5\":\"6.223672\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"5.25\",\"5\":\"5.827604\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"5.50\",\"5\":\"4.352723\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"3.25\",\"5\":\"5.351926\"},{\"1\":\"14\",\"2\":\"no\",\"3\":\"control\",\"4\":\"2.75\",\"5\":\"5.171587\"},{\"1\":\"15\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"5.75\",\"5\":\"7.578029\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"5.75\",\"5\":\"7.532928\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"3.25\",\"5\":\"2.851782\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"3.25\",\"5\":\"5.993305\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"5.25\",\"5\":\"6.134566\"},{\"1\":\"13\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"3.00\",\"5\":\"6.628292\"},{\"1\":\"13\",\"2\":\"no\",\"3\":\"control\",\"4\":\"4.75\",\"5\":\"7.156260\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.75\",\"5\":\"6.941121\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"3.75\",\"5\":\"3.474990\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.25\",\"5\":\"3.990403\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"control\",\"4\":\"5.25\",\"5\":\"6.909764\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.75\",\"5\":\"5.250589\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.75\",\"5\":\"4.623103\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"3.00\",\"5\":\"6.118921\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"control\",\"4\":\"4.00\",\"5\":\"4.916206\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"2.00\",\"5\":\"1.000000\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"6.00\",\"5\":\"6.316840\"},{\"1\":\"1\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"2.75\",\"5\":\"1.462389\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"5.50\",\"5\":\"6.061523\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"3.00\",\"5\":\"4.620474\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"control\",\"4\":\"4.00\",\"5\":\"4.633540\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"3.50\",\"5\":\"5.122722\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"3.00\",\"5\":\"3.950663\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.75\",\"5\":\"4.416138\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.50\",\"5\":\"6.541928\"},{\"1\":\"10\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"4.00\",\"5\":\"2.683608\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.75\",\"5\":\"4.963798\"},{\"1\":\"5\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"5.75\",\"5\":\"8.512563\"},{\"1\":\"10\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.25\",\"5\":\"2.170991\"},{\"1\":\"8\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"4.00\",\"5\":\"1.000000\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"3.00\",\"5\":\"2.763689\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"3.25\",\"5\":\"1.854345\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"5.25\",\"5\":\"4.383383\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.00\",\"5\":\"4.394819\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"4.00\",\"5\":\"3.959485\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"3.50\",\"5\":\"6.343413\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"5.50\",\"5\":\"7.042022\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"6.50\",\"5\":\"7.961551\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"3.50\",\"5\":\"5.668190\"},{\"1\":\"21\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"3.50\",\"5\":\"6.141086\"},{\"1\":\"9\",\"2\":\"no\",\"3\":\"control\",\"4\":\"4.00\",\"5\":\"3.575320\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"control\",\"4\":\"3.00\",\"5\":\"3.519456\"},{\"1\":\"9\",\"2\":\"no\",\"3\":\"control\",\"4\":\"5.00\",\"5\":\"7.021623\"},{\"1\":\"15\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"6.50\",\"5\":\"8.085269\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"6.25\",\"5\":\"7.084477\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"2.75\",\"5\":\"2.206308\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"2.00\",\"5\":\"4.791258\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"5.25\",\"5\":\"8.182959\"},{\"1\":\"16\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.75\",\"5\":\"6.481829\"},{\"1\":\"7\",\"2\":\"no\",\"3\":\"control\",\"4\":\"3.25\",\"5\":\"3.821793\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"3.25\",\"5\":\"3.886707\"},{\"1\":\"17\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.75\",\"5\":\"5.243956\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.25\",\"5\":\"7.274479\"},{\"1\":\"13\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"3.00\",\"5\":\"2.527853\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"5.00\",\"5\":\"5.729213\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"6.00\",\"5\":\"7.694568\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.00\",\"5\":\"5.367550\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"5.25\",\"5\":\"5.810933\"},{\"1\":\"18\",\"2\":\"no\",\"3\":\"control\",\"4\":\"2.75\",\"5\":\"1.773107\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.50\",\"5\":\"3.835568\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"2.25\",\"5\":\"1.769015\"},{\"1\":\"5\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"3.25\",\"5\":\"3.050349\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"5.50\",\"5\":\"6.155585\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"2.50\",\"5\":\"4.084005\"},{\"1\":\"13\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"1.50\",\"5\":\"1.835718\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"3.75\",\"5\":\"3.914796\"},{\"1\":\"5\",\"2\":\"no\",\"3\":\"control\",\"4\":\"3.00\",\"5\":\"4.844133\"},{\"1\":\"5\",\"2\":\"no\",\"3\":\"control\",\"4\":\"4.25\",\"5\":\"4.945848\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"3.25\",\"5\":\"2.702555\"},{\"1\":\"16\",\"2\":\"no\",\"3\":\"control\",\"4\":\"7.00\",\"5\":\"10.000000\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.00\",\"5\":\"4.056673\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"5.50\",\"5\":\"4.653024\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.75\",\"5\":\"4.636781\"},{\"1\":\"7\",\"2\":\"no\",\"3\":\"control\",\"4\":\"5.50\",\"5\":\"5.547250\"},{\"1\":\"10\",\"2\":\"no\",\"3\":\"control\",\"4\":\"3.25\",\"5\":\"4.617935\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.75\",\"5\":\"4.588614\"},{\"1\":\"14\",\"2\":\"no\",\"3\":\"control\",\"4\":\"5.50\",\"5\":\"7.154327\"},{\"1\":\"8\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"4.25\",\"5\":\"1.137742\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.00\",\"5\":\"1.751485\"},{\"1\":\"10\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.50\",\"5\":\"5.869801\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.00\",\"5\":\"4.398392\"},{\"1\":\"7\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.25\",\"5\":\"6.678895\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"6.00\",\"5\":\"8.286313\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"3.00\",\"5\":\"3.910157\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"5.75\",\"5\":\"5.619188\"},{\"1\":\"8\",\"2\":\"no\",\"3\":\"control\",\"4\":\"3.25\",\"5\":\"4.352709\"},{\"1\":\"7\",\"2\":\"no\",\"3\":\"control\",\"4\":\"3.25\",\"5\":\"2.728237\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.50\",\"5\":\"7.012092\"},{\"1\":\"13\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.00\",\"5\":\"5.758558\"},{\"1\":\"23\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"5.50\",\"5\":\"8.037619\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.00\",\"5\":\"4.980741\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.75\",\"5\":\"5.950005\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"5.00\",\"5\":\"6.204879\"},{\"1\":\"14\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"3.50\",\"5\":\"1.479750\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"6.00\",\"5\":\"7.068938\"},{\"1\":\"12\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"2.50\",\"5\":\"3.108798\"},{\"1\":\"15\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.00\",\"5\":\"5.309824\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"5.25\",\"5\":\"7.751116\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"2.00\",\"5\":\"2.652934\"},{\"1\":\"15\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"3.75\",\"5\":\"1.768034\"},{\"1\":\"13\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"3.75\",\"5\":\"2.390063\"},{\"1\":\"20\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"3.00\",\"5\":\"4.252119\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.00\",\"5\":\"6.136307\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.75\",\"5\":\"4.029761\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.00\",\"5\":\"5.735141\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.75\",\"5\":\"6.247456\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.50\",\"5\":\"5.072741\"},{\"1\":\"13\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"2.75\",\"5\":\"2.140178\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"6.25\",\"5\":\"7.372685\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.00\",\"5\":\"6.151249\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"control\",\"4\":\"5.00\",\"5\":\"6.332064\"},{\"1\":\"16\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.75\",\"5\":\"6.386775\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"5.50\",\"5\":\"7.008749\"},{\"1\":\"8\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"4.75\",\"5\":\"5.007537\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.00\",\"5\":\"4.325757\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"3.25\",\"5\":\"4.560664\"},{\"1\":\"9\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"3.25\",\"5\":\"5.301583\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"control\",\"4\":\"5.50\",\"5\":\"7.142415\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.50\",\"5\":\"7.288590\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"7.25\",\"5\":\"10.000000\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"3.75\",\"5\":\"5.567391\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"2.75\",\"5\":\"4.002713\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.50\",\"5\":\"6.267628\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"2.75\",\"5\":\"1.591352\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"3.50\",\"5\":\"5.420867\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.25\",\"5\":\"6.327989\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"5.00\",\"5\":\"6.010028\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"3.75\",\"5\":\"4.976351\"},{\"1\":\"16\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"4.50\",\"5\":\"5.816395\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"6.00\",\"5\":\"8.940256\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.75\",\"5\":\"5.375664\"},{\"1\":\"17\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.50\",\"5\":\"6.234840\"},{\"1\":\"8\",\"2\":\"no\",\"3\":\"control\",\"4\":\"2.75\",\"5\":\"2.745730\"},{\"1\":\"12\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"3.50\",\"5\":\"2.808001\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.50\",\"5\":\"4.833959\"},{\"1\":\"15\",\"2\":\"no\",\"3\":\"control\",\"4\":\"3.00\",\"5\":\"2.609233\"},{\"1\":\"16\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.75\",\"5\":\"5.817862\"},{\"1\":\"8\",\"2\":\"no\",\"3\":\"control\",\"4\":\"5.75\",\"5\":\"8.007690\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.50\",\"5\":\"5.799799\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"5.25\",\"5\":\"6.770935\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"5.75\",\"5\":\"3.393202\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.75\",\"5\":\"6.854968\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.50\",\"5\":\"7.877185\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"3.00\",\"5\":\"3.928530\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"3.00\",\"5\":\"4.648448\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"3.75\",\"5\":\"4.282463\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"3.50\",\"5\":\"4.128321\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.50\",\"5\":\"5.102619\"},{\"1\":\"15\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"4.75\",\"5\":\"1.834901\"},{\"1\":\"4\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"4.00\",\"5\":\"4.046865\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"4.50\",\"5\":\"2.464420\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"3.00\",\"5\":\"2.612521\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.25\",\"5\":\"4.438139\"},{\"1\":\"8\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.50\",\"5\":\"5.670909\"},{\"1\":\"10\",\"2\":\"no\",\"3\":\"control\",\"4\":\"3.75\",\"5\":\"4.345202\"},{\"1\":\"10\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"4.00\",\"5\":\"4.025968\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"5.25\",\"5\":\"5.809696\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.00\",\"5\":\"5.853488\"},{\"1\":\"10\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"4.25\",\"5\":\"2.846640\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"5.50\",\"5\":\"5.993879\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.25\",\"5\":\"5.787301\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"3.00\",\"5\":\"4.558428\"},{\"1\":\"13\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"5.75\",\"5\":\"7.029757\"},{\"1\":\"15\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"4.50\",\"5\":\"3.369911\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"5.50\",\"5\":\"5.998080\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.25\",\"5\":\"5.820974\"},{\"1\":\"14\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"5.00\",\"5\":\"4.061854\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"2.75\",\"5\":\"2.891384\"},{\"1\":\"7\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"4.00\",\"5\":\"4.642953\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"control\",\"4\":\"2.75\",\"5\":\"2.374020\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"3.50\",\"5\":\"5.542766\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"5.25\",\"5\":\"4.852981\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"5.00\",\"5\":\"7.493793\"},{\"1\":\"10\",\"2\":\"no\",\"3\":\"control\",\"4\":\"5.00\",\"5\":\"6.313676\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"5.50\",\"5\":\"6.184897\"},{\"1\":\"7\",\"2\":\"no\",\"3\":\"control\",\"4\":\"5.00\",\"5\":\"6.196171\"},{\"1\":\"18\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"3.75\",\"5\":\"4.208125\"},{\"1\":\"17\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"5.50\",\"5\":\"6.991875\"},{\"1\":\"13\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"3.75\",\"5\":\"2.671960\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"5.50\",\"5\":\"6.496267\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.00\",\"5\":\"5.006706\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"5.00\",\"5\":\"5.928143\"},{\"1\":\"10\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"4.50\",\"5\":\"1.987325\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"2.75\",\"5\":\"5.306442\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"3.50\",\"5\":\"2.603075\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.25\",\"5\":\"5.619073\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.00\",\"5\":\"4.897040\"},{\"1\":\"16\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"3.00\",\"5\":\"3.210468\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"7.00\",\"5\":\"8.155126\"},{\"1\":\"9\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"5.25\",\"5\":\"5.350983\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.50\",\"5\":\"3.964301\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"2.75\",\"5\":\"4.392203\"},{\"1\":\"15\",\"2\":\"no\",\"3\":\"control\",\"4\":\"3.25\",\"5\":\"4.146906\"},{\"1\":\"16\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"7.50\",\"5\":\"10.000000\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.50\",\"5\":\"5.519414\"},{\"1\":\"9\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.25\",\"5\":\"6.119183\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"6.50\",\"5\":\"6.318267\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"5.75\",\"5\":\"6.849301\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.75\",\"5\":\"6.406149\"},{\"1\":\"14\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"5.75\",\"5\":\"7.924148\"},{\"1\":\"8\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"5.25\",\"5\":\"6.658999\"},{\"1\":\"14\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"3.50\",\"5\":\"4.936396\"},{\"1\":\"15\",\"2\":\"no\",\"3\":\"control\",\"4\":\"2.25\",\"5\":\"1.000000\"},{\"1\":\"10\",\"2\":\"no\",\"3\":\"control\",\"4\":\"3.75\",\"5\":\"4.123743\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"2.75\",\"5\":\"3.871325\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"3.75\",\"5\":\"3.082417\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"3.75\",\"5\":\"4.700358\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"3.25\",\"5\":\"4.501737\"},{\"1\":\"10\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"5.50\",\"5\":\"6.546874\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"4.75\",\"5\":\"5.738714\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"3.75\",\"5\":\"1.849618\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"5.00\",\"5\":\"5.290361\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.50\",\"5\":\"7.371075\"},{\"1\":\"13\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"3.25\",\"5\":\"3.907558\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.00\",\"5\":\"4.234866\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"control\",\"4\":\"2.75\",\"5\":\"2.114546\"},{\"1\":\"20\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"5.25\",\"5\":\"3.136907\"},{\"1\":\"7\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"4.00\",\"5\":\"4.672823\"},{\"1\":\"13\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.00\",\"5\":\"5.949233\"},{\"1\":\"16\",\"2\":\"no\",\"3\":\"control\",\"4\":\"2.75\",\"5\":\"2.403313\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"5.50\",\"5\":\"7.070405\"},{\"1\":\"19\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.50\",\"5\":\"4.724807\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"7.00\",\"5\":\"9.398812\"},{\"1\":\"9\",\"2\":\"no\",\"3\":\"control\",\"4\":\"6.00\",\"5\":\"6.581820\"},{\"1\":\"13\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.75\",\"5\":\"4.270891\"},{\"1\":\"6\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"3.50\",\"5\":\"2.489996\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"control\",\"4\":\"4.75\",\"5\":\"6.111681\"},{\"1\":\"13\",\"2\":\"no\",\"3\":\"control\",\"4\":\"6.00\",\"5\":\"8.339752\"},{\"1\":\"6\",\"2\":\"no\",\"3\":\"control\",\"4\":\"3.00\",\"5\":\"3.606132\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"5.50\",\"5\":\"6.526716\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.50\",\"5\":\"5.035256\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"3.25\",\"5\":\"3.866240\"},{\"1\":\"10\",\"2\":\"no\",\"3\":\"control\",\"4\":\"4.25\",\"5\":\"7.230517\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"3.50\",\"5\":\"3.667156\"},{\"1\":\"7\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"2.25\",\"5\":\"1.310174\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"control\",\"4\":\"4.75\",\"5\":\"6.347251\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"5.00\",\"5\":\"6.541694\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.00\",\"5\":\"5.846384\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"2.25\",\"5\":\"2.238402\"},{\"1\":\"9\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"3.00\",\"5\":\"2.681164\"},{\"1\":\"14\",\"2\":\"no\",\"3\":\"control\",\"4\":\"5.00\",\"5\":\"7.433464\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.00\",\"5\":\"5.198604\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"2.50\",\"5\":\"2.538843\"},{\"1\":\"13\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.50\",\"5\":\"5.094593\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"2.75\",\"5\":\"4.489576\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.75\",\"5\":\"7.761462\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"3.75\",\"5\":\"4.585051\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"5.25\",\"5\":\"4.365277\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"3.50\",\"5\":\"5.277698\"},{\"1\":\"13\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.00\",\"5\":\"4.184738\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"2.75\",\"5\":\"2.982358\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"5.50\",\"5\":\"6.141235\"},{\"1\":\"15\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"3.75\",\"5\":\"1.706067\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"6.00\",\"5\":\"7.505538\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.75\",\"5\":\"6.715460\"},{\"1\":\"13\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"3.25\",\"5\":\"5.296886\"},{\"1\":\"3\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"2.50\",\"5\":\"1.238477\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"5.00\",\"5\":\"4.844318\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"2.25\",\"5\":\"2.317574\"},{\"1\":\"15\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.75\",\"5\":\"7.151195\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"5.00\",\"5\":\"5.425042\"},{\"1\":\"21\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"2.75\",\"5\":\"4.562125\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"3.00\",\"5\":\"2.788964\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.25\",\"5\":\"5.234731\"},{\"1\":\"9\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"3.00\",\"5\":\"5.852368\"},{\"1\":\"15\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"6.50\",\"5\":\"6.992390\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"6.00\",\"5\":\"7.227884\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"5.50\",\"5\":\"7.692990\"},{\"1\":\"20\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"7.75\",\"5\":\"10.000000\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.00\",\"5\":\"6.110274\"},{\"1\":\"14\",\"2\":\"no\",\"3\":\"control\",\"4\":\"3.75\",\"5\":\"4.786212\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"5.00\",\"5\":\"4.000628\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"4.00\",\"5\":\"2.793378\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.00\",\"5\":\"5.334913\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.25\",\"5\":\"3.294563\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"3.25\",\"5\":\"3.713328\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"3.50\",\"5\":\"2.825348\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"5.00\",\"5\":\"4.797853\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.00\",\"5\":\"4.975132\"},{\"1\":\"10\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"1.75\",\"5\":\"2.645935\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"5.00\",\"5\":\"8.175462\"},{\"1\":\"10\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"3.00\",\"5\":\"1.559648\"},{\"1\":\"14\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"3.75\",\"5\":\"3.550596\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.50\",\"5\":\"6.811079\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"3.50\",\"5\":\"5.646206\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"3.25\",\"5\":\"5.277303\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.00\",\"5\":\"5.377978\"},{\"1\":\"14\",\"2\":\"no\",\"3\":\"control\",\"4\":\"4.00\",\"5\":\"3.312699\"},{\"1\":\"10\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"3.25\",\"5\":\"2.917811\"},{\"1\":\"10\",\"2\":\"no\",\"3\":\"control\",\"4\":\"3.75\",\"5\":\"4.927604\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"3.50\",\"5\":\"6.297673\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"3.75\",\"5\":\"7.792462\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.50\",\"5\":\"5.341631\"},{\"1\":\"4\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"3.25\",\"5\":\"1.000000\"},{\"1\":\"15\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"3.75\",\"5\":\"3.021541\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"3.25\",\"5\":\"5.411968\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.00\",\"5\":\"6.246341\"},{\"1\":\"21\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.25\",\"5\":\"7.437452\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.00\",\"5\":\"6.496936\"},{\"1\":\"10\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"4.25\",\"5\":\"4.342733\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.50\",\"5\":\"7.348594\"},{\"1\":\"14\",\"2\":\"no\",\"3\":\"control\",\"4\":\"6.00\",\"5\":\"9.329498\"},{\"1\":\"6\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"3.50\",\"5\":\"6.075901\"},{\"1\":\"13\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"3.25\",\"5\":\"5.014028\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.75\",\"5\":\"5.461092\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.75\",\"5\":\"3.302036\"},{\"1\":\"17\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"4.50\",\"5\":\"3.127521\"},{\"1\":\"15\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.25\",\"5\":\"6.325022\"},{\"1\":\"10\",\"2\":\"no\",\"3\":\"control\",\"4\":\"5.25\",\"5\":\"6.412055\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"2.75\",\"5\":\"3.374514\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"3.25\",\"5\":\"4.180109\"},{\"1\":\"13\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"3.50\",\"5\":\"2.688703\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.25\",\"5\":\"5.622933\"},{\"1\":\"9\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"4.75\",\"5\":\"2.886261\"},{\"1\":\"15\",\"2\":\"no\",\"3\":\"control\",\"4\":\"3.75\",\"5\":\"3.883550\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.25\",\"5\":\"6.335078\"},{\"1\":\"10\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"5.25\",\"5\":\"3.939259\"},{\"1\":\"13\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"3.50\",\"5\":\"3.529489\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"2.75\",\"5\":\"4.016810\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"3.00\",\"5\":\"3.563214\"},{\"1\":\"13\",\"2\":\"no\",\"3\":\"control\",\"4\":\"5.00\",\"5\":\"6.294166\"},{\"1\":\"13\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"2.75\",\"5\":\"2.545488\"},{\"1\":\"15\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"4.75\",\"5\":\"4.086781\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.50\",\"5\":\"5.345021\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"5.25\",\"5\":\"7.555472\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"3.00\",\"5\":\"3.938185\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"5.00\",\"5\":\"5.555334\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.75\",\"5\":\"4.963669\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.00\",\"5\":\"4.681328\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.50\",\"5\":\"5.148700\"},{\"1\":\"13\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"4.75\",\"5\":\"4.356163\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.75\",\"5\":\"8.057127\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.00\",\"5\":\"4.689057\"},{\"1\":\"20\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.25\",\"5\":\"6.209530\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"5.75\",\"5\":\"5.666832\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"5.50\",\"5\":\"7.957438\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"3.50\",\"5\":\"4.498674\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.25\",\"5\":\"5.391407\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.00\",\"5\":\"4.295877\"},{\"1\":\"17\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.75\",\"5\":\"5.181682\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"3.00\",\"5\":\"1.000000\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"6.00\",\"5\":\"8.106811\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"3.50\",\"5\":\"6.590869\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.00\",\"5\":\"5.563063\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"3.25\",\"5\":\"2.715957\"},{\"1\":\"17\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.00\",\"5\":\"5.743442\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.00\",\"5\":\"4.770749\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"3.25\",\"5\":\"4.205387\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"3.50\",\"5\":\"7.102065\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"3.75\",\"5\":\"6.464528\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"5.75\",\"5\":\"6.811115\"},{\"1\":\"8\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"3.25\",\"5\":\"3.988123\"},{\"1\":\"20\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"3.25\",\"5\":\"5.255100\"},{\"1\":\"16\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"3.75\",\"5\":\"4.636838\"},{\"1\":\"21\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.00\",\"5\":\"5.866802\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"3.50\",\"5\":\"4.367423\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"control\",\"4\":\"5.00\",\"5\":\"6.842548\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"5.00\",\"5\":\"7.403783\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"3.75\",\"5\":\"3.735139\"},{\"1\":\"7\",\"2\":\"no\",\"3\":\"control\",\"4\":\"2.50\",\"5\":\"2.301165\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"5.25\",\"5\":\"4.414882\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"3.00\",\"5\":\"5.047734\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.00\",\"5\":\"4.273408\"},{\"1\":\"14\",\"2\":\"no\",\"3\":\"control\",\"4\":\"5.75\",\"5\":\"5.505137\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.75\",\"5\":\"6.233301\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.00\",\"5\":\"7.097395\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"2.25\",\"5\":\"1.155648\"},{\"1\":\"15\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.50\",\"5\":\"5.795221\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"2.75\",\"5\":\"4.788544\"},{\"1\":\"8\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"3.75\",\"5\":\"2.013893\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"6.00\",\"5\":\"7.090021\"},{\"1\":\"8\",\"2\":\"no\",\"3\":\"control\",\"4\":\"5.00\",\"5\":\"6.589034\"},{\"1\":\"10\",\"2\":\"no\",\"3\":\"control\",\"4\":\"4.25\",\"5\":\"4.392529\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"3.75\",\"5\":\"2.558263\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.50\",\"5\":\"6.744933\"},{\"1\":\"17\",\"2\":\"no\",\"3\":\"control\",\"4\":\"4.00\",\"5\":\"5.917828\"},{\"1\":\"7\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.50\",\"5\":\"7.573499\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"3.25\",\"5\":\"1.601779\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.50\",\"5\":\"7.642767\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"3.75\",\"5\":\"5.330771\"},{\"1\":\"7\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"4.25\",\"5\":\"2.956369\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"5.25\",\"5\":\"6.878939\"},{\"1\":\"8\",\"2\":\"no\",\"3\":\"control\",\"4\":\"3.25\",\"5\":\"3.933378\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.25\",\"5\":\"5.778823\"},{\"1\":\"13\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"5.00\",\"5\":\"4.732006\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"5.75\",\"5\":\"7.170590\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"5.50\",\"5\":\"5.589805\"},{\"1\":\"6\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"2.75\",\"5\":\"1.580373\"},{\"1\":\"13\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.75\",\"5\":\"6.760043\"},{\"1\":\"14\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"2.75\",\"5\":\"1.000000\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"3.50\",\"5\":\"5.130432\"},{\"1\":\"6\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"3.25\",\"5\":\"2.789426\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"5.75\",\"5\":\"8.121209\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.75\",\"5\":\"5.361397\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"5.50\",\"5\":\"5.682970\"},{\"1\":\"13\",\"2\":\"no\",\"3\":\"control\",\"4\":\"5.00\",\"5\":\"5.395141\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"5.25\",\"5\":\"5.267099\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.25\",\"5\":\"6.474832\"},{\"1\":\"7\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"3.75\",\"5\":\"4.806693\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"3.50\",\"5\":\"4.936246\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.75\",\"5\":\"6.774041\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"3.75\",\"5\":\"4.355263\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"3.50\",\"5\":\"4.877094\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"control\",\"4\":\"3.25\",\"5\":\"5.160009\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"3.50\",\"5\":\"5.099011\"},{\"1\":\"8\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"2.25\",\"5\":\"1.000000\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"5.50\",\"5\":\"8.044984\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.25\",\"5\":\"5.228126\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.25\",\"5\":\"5.501536\"},{\"1\":\"9\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.50\",\"5\":\"6.250516\"},{\"1\":\"10\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"2.75\",\"5\":\"2.574248\"},{\"1\":\"2\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.00\",\"5\":\"5.718363\"},{\"1\":\"20\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.00\",\"5\":\"4.028561\"},{\"1\":\"9\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"5.00\",\"5\":\"5.430161\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"4.50\",\"5\":\"4.886423\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"4.25\",\"5\":\"2.691592\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.75\",\"5\":\"8.685453\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"6.25\",\"5\":\"5.856230\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"5.75\",\"5\":\"2.387690\"},{\"1\":\"20\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"5.75\",\"5\":\"8.394679\"},{\"1\":\"6\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"5.00\",\"5\":\"5.546165\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.75\",\"5\":\"6.764307\"},{\"1\":\"5\",\"2\":\"no\",\"3\":\"control\",\"4\":\"5.00\",\"5\":\"6.180635\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.00\",\"5\":\"3.935280\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.00\",\"5\":\"3.974702\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"5.25\",\"5\":\"3.931147\"},{\"1\":\"10\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"5.75\",\"5\":\"3.990470\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.50\",\"5\":\"5.655197\"},{\"1\":\"13\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"3.25\",\"5\":\"1.955259\"},{\"1\":\"10\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"2.75\",\"5\":\"2.661602\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"6.25\",\"5\":\"7.033872\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"3.75\",\"5\":\"5.605718\"},{\"1\":\"16\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.00\",\"5\":\"6.804893\"},{\"1\":\"13\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"2.25\",\"5\":\"3.310555\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"3.75\",\"5\":\"5.020263\"},{\"1\":\"9\",\"2\":\"no\",\"3\":\"control\",\"4\":\"4.50\",\"5\":\"5.901529\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"5.25\",\"5\":\"6.638662\"},{\"1\":\"10\",\"2\":\"no\",\"3\":\"control\",\"4\":\"5.25\",\"5\":\"6.519300\"},{\"1\":\"9\",\"2\":\"no\",\"3\":\"control\",\"4\":\"4.00\",\"5\":\"4.933640\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"3.50\",\"5\":\"2.643269\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"5.25\",\"5\":\"6.936383\"},{\"1\":\"13\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"3.25\",\"5\":\"5.683358\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"6.50\",\"5\":\"8.748777\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"4.75\",\"5\":\"2.717786\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"2.50\",\"5\":\"4.360039\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"3.50\",\"5\":\"4.265381\"},{\"1\":\"13\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.50\",\"5\":\"6.393520\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"6.50\",\"5\":\"7.082540\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"5.25\",\"5\":\"6.209874\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.75\",\"5\":\"6.575522\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.50\",\"5\":\"3.000576\"},{\"1\":\"13\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"3.25\",\"5\":\"2.496913\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"3.25\",\"5\":\"3.201963\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.00\",\"5\":\"4.806228\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"5.00\",\"5\":\"6.624262\"},{\"1\":\"16\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"2.50\",\"5\":\"1.678209\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.50\",\"5\":\"2.478041\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"6.50\",\"5\":\"7.135388\"},{\"1\":\"9\",\"2\":\"no\",\"3\":\"control\",\"4\":\"3.50\",\"5\":\"5.099300\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"3.25\",\"5\":\"5.930034\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"3.75\",\"5\":\"7.315202\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"3.75\",\"5\":\"4.939468\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.00\",\"5\":\"3.972892\"},{\"1\":\"10\",\"2\":\"no\",\"3\":\"control\",\"4\":\"4.75\",\"5\":\"8.530662\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.75\",\"5\":\"7.378405\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"5.00\",\"5\":\"4.870092\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"3.50\",\"5\":\"4.165499\"},{\"1\":\"4\",\"2\":\"no\",\"3\":\"control\",\"4\":\"3.25\",\"5\":\"2.357299\"},{\"1\":\"8\",\"2\":\"no\",\"3\":\"control\",\"4\":\"6.00\",\"5\":\"5.875934\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.25\",\"5\":\"6.073045\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"control\",\"4\":\"3.25\",\"5\":\"4.685541\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"control\",\"4\":\"3.00\",\"5\":\"3.065955\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"3.75\",\"5\":\"4.935506\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"5.00\",\"5\":\"2.627988\"},{\"1\":\"8\",\"2\":\"no\",\"3\":\"control\",\"4\":\"4.75\",\"5\":\"7.192335\"},{\"1\":\"5\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"3.00\",\"5\":\"3.439418\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"3.25\",\"5\":\"2.573040\"},{\"1\":\"10\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"3.25\",\"5\":\"3.666294\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"5.00\",\"5\":\"5.871287\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.75\",\"5\":\"4.804418\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"5.00\",\"5\":\"6.517382\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"6.00\",\"5\":\"7.323796\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"3.50\",\"5\":\"4.417015\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.25\",\"5\":\"3.411787\"},{\"1\":\"13\",\"2\":\"no\",\"3\":\"control\",\"4\":\"5.75\",\"5\":\"7.253936\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"3.25\",\"5\":\"3.072896\"},{\"1\":\"7\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"2.25\",\"5\":\"2.513720\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"5.25\",\"5\":\"6.873633\"},{\"1\":\"19\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.75\",\"5\":\"5.859310\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"3.50\",\"5\":\"3.833097\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.00\",\"5\":\"5.407823\"},{\"1\":\"7\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"6.00\",\"5\":\"5.310486\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.25\",\"5\":\"5.603346\"},{\"1\":\"13\",\"2\":\"no\",\"3\":\"control\",\"4\":\"2.00\",\"5\":\"1.839702\"},{\"1\":\"10\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"3.00\",\"5\":\"5.188950\"},{\"1\":\"15\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"5.00\",\"5\":\"9.433706\"},{\"1\":\"14\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.75\",\"5\":\"7.069216\"},{\"1\":\"11\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"5.25\",\"5\":\"7.670233\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"3.25\",\"5\":\"5.310485\"},{\"1\":\"14\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"4.25\",\"5\":\"4.747775\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.00\",\"5\":\"3.530102\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"3.00\",\"5\":\"4.090011\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.25\",\"5\":\"5.448243\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"4.50\",\"5\":\"5.289513\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"3.75\",\"5\":\"2.836264\"},{\"1\":\"15\",\"2\":\"yes\",\"3\":\"positive\",\"4\":\"3.50\",\"5\":\"3.187367\"},{\"1\":\"18\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"5.50\",\"5\":\"4.804216\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"control\",\"4\":\"5.00\",\"5\":\"5.240247\"},{\"1\":\"7\",\"2\":\"no\",\"3\":\"control\",\"4\":\"4.75\",\"5\":\"6.127947\"},{\"1\":\"10\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"5.00\",\"5\":\"6.033116\"},{\"1\":\"12\",\"2\":\"no\",\"3\":\"control\",\"4\":\"4.75\",\"5\":\"4.840261\"},{\"1\":\"9\",\"2\":\"no\",\"3\":\"positive\",\"4\":\"4.50\",\"5\":\"6.808615\"},{\"1\":\"16\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"5.25\",\"5\":\"7.439035\"},{\"1\":\"17\",\"2\":\"yes\",\"3\":\"negative\",\"4\":\"4.75\",\"5\":\"7.469343\"},{\"1\":\"9\",\"2\":\"no\",\"3\":\"negative\",\"4\":\"3.75\",\"5\":\"3.090023\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\n\n## One-sample t-test\n\nThe one-sample t-test is used to compare the mean of a single sample to a known value (e.g., a population mean).\nIn this example, we'll test if the average number of hours per week that people spend consuming news is significantly different from 14 hours (there is no particular reason for this value, it's just an example).\n\nFirst, let's look at the mean and standard deviation of `news_consumption`.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd |> \n  summarise(M = mean(news_consumption),\n            SD = sd(news_consumption))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"M\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"SD\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"14.25667\",\"2\":\"3.649153\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\n\nThis shows that the mean number of hours spent consuming news per week is higher than 10. \nWith the one-sample t-test we can test if this difference is statistically significant.\nThe formula for the one-sample t-test is `dependent_variable ~ 1`, where `1` indicates that there is no grouping variable (this will make sense when you see the formula for the independent samples t-test).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(news_consumption ~ 1, mu = 14, data=d)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  news_consumption\nt = 1.7229, df = 599, p-value = 0.08543\nalternative hypothesis: true mean is not equal to 14\n95 percent confidence interval:\n 13.96409 14.54925\nsample estimates:\nmean of x \n 14.25667 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\nThe results show that the mean number of hours spent consuming news ($M = 14.26, SD = 3.65$) is not significantly different from 14 hours, $t(599) = 1.72, p = 0.085$.\nSo even though the mean is higher than 14 hours, based on our data we cannot conclude that this difference is statistically significant.\n\n## Independent samples t-test\n\nThe independent samples t-test is used to compare the means between two independent groups.\nHere we compare `news_consumption` *between* people who have a subscription to a newspaper and those who don't (`np_subscription`).\n\nLet's first look at the means and standard deviations for each group.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd |>\n  group_by(np_subscription) %>%\n  summarise(M = mean(news_consumption),\n            SD = sd(news_consumption))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"np_subscription\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"M\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"SD\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"no\",\"2\":\"11.33840\",\"3\":\"3.290561\"},{\"1\":\"yes\",\"2\":\"16.53412\",\"3\":\"1.851526\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\n\nThis shows that the mean number of hours spent consuming news is higher for people with a subscription than for those without.\nWith the independent samples t-test we can test if this difference is statistically significant.\n\nHowever, we need to check one thing first!\nFor the independent samples t-test, we need to indicate whether the variances between the two groups are equal.\nFrom the standard deviations we already know that they are not identical.\nTo test this formally, we can use Levene's test.\nThe formula for Levene's test is `dependent_variable ~ grouping_variable`.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleveneTest(news_consumption ~ np_subscription, data = d)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Df\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"F value\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>F)\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"1\",\"2\":\"70.62746\",\"3\":\"3.156186e-16\",\"_rn_\":\"group\"},{\"1\":\"598\",\"2\":\"NA\",\"3\":\"NA\",\"_rn_\":\"\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\n\nThe Levene's test is significant (p < 0.001), which means that the variances are not equal.\nNow, we can perform the independent samples t-test with the argument `var.equal = FALSE`.[^var_equal]\nThe formula for the independent samples t-test is `dependent_variable ~ grouping_variable`.\n\n[^var_equal]: \nIf the variances are equal, you set `var.equal = TRUE`.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(news_consumption ~ np_subscription, data = d, var.equal = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  news_consumption by np_subscription\nt = -22.93, df = 388.95, p-value < 2.2e-16\nalternative hypothesis: true difference in means between group no and group yes is not equal to 0\n95 percent confidence interval:\n -5.641215 -4.750228\nsample estimates:\n mean in group no mean in group yes \n         11.33840          16.53412 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\nThe results show that the mean number of hours spent consuming news is significantly different between people with (\n$M_1 = 16.53, SD = 1.85$) and without ($M_0 = 11.34, SD = 3.29$) a subscription to a national newspaper, $t(388.95) = -22.93, p < 0.001$.\n\n## Paired samples t-test\n\nThe paired samples t-test is used to compare the means within subjects at two different time points or under two different conditions.\nIn this example, we'll test if the trust in journalism (`trust_t1` and `trust_t2`) significantly changed after the experiment.\nWe focusing on the group that watched the *positive* movie, to see if this had a positive effect on trust.[^positive]:\n\n[^positive]:\nWe focus on one group, because we expect trust to change in different directions depending on the movie (e.g., increase after watching a positive movie, decrease after watching a negative movie). \nNote that in reality, when you have both repeated measures and multiple groups, you might want to use a mixed design [ANOVA](./anova.qmd) instead.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd_positive <- filter(d, experiment_group == \"positive\")\n```\n:::\n\n\n\n\nFirst, let's look at the means and standard deviations for each time point.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd_positive |>\n  summarise(M1 = mean(trust_t1),\n            SD1 = sd(trust_t1),\n            M2 = mean(trust_t2),\n            SD2 = sd(trust_t2))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"M1\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"SD1\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"M2\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"SD2\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"4.23\",\"2\":\"1.077511\",\"3\":\"5.633776\",\"4\":\"1.659792\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\n\nNow, let's perform the paired samples t-test.\nNotice that this time we don't have a grouping variable, like `np_subscription` above.\nInstead, our observations are *paired* within the same row (i.e. participant), so we need to specify the two variables that we want to compare.\nThe formula for this is `Pair(t1, t2) ~ 1`.\nWe use the argument `paired = TRUE` to indicate that the observations are paired.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(Pair(trust_t1, trust_t2) ~ 1, data = d_positive)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  Pair(trust_t1, trust_t2)\nt = -17.724, df = 199, p-value < 2.2e-16\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n -1.559961 -1.247592\nsample estimates:\nmean difference \n      -1.403776 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\nThe results show that the trust in journalism significantly increased[^increased] after watching the *positive* movie, $t(199.00) = -17.72, p < 0.001$.\n\n[^increased]:\nWe know that it increased from the means that we calculated above.\nWhat might be confusing is that the t-test reports a negative value for the mean difference.\nThis is because the t-test is based on the difference between the two means, and the difference is calculated as `trust_t1 - trust_t2`.\n\n\n## Two-sided vs one-sided t-test\n\nBy default, the t-test is two-sided, which means that we don't care about the direction of difference between the means.\nOur one-sample t-test tested whether the mean was *less OR greater* than 10 hours.\nOur independent samples t-test tested whether the first mean was *less OR greater* than the second mean.\nAnd our paired samples t-test tested whether the difference between the two means (trust_t1 - trust_t2) was *less OR greater* than zero.\n\nIf you have a specific hypothesis about the direction of the difference, you can also perform a one-sided t-test.\nBy doing so, you increase the power of the test, because you only need to reject the null hypothesis in one direction.\nThe following figures show how a one-sided t-test puts all the probability in one tail of the distribution, which means that with the same level of significance (e.g., $\\alpha = 0.05$), you can reject the null hypothesis with a smaller t-value.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](t-test_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n\n\n### Word of caution\n\nUsing a one-sided test is only valid if you have a strong, justifiable reason to expect that the difference will be in a specific direction.\nThis expectation should be grounded in theory, and formulated a priori, before you look at the data. \n\nUsing a one-sided test after examining the data, or simply to achieve statistical significance, is a serious violation of research ethics. It artificially inflates the chances of rejecting the null hypothesis by ignoring potential effects in the other direction. This increases the risk of Type I error (a false positive) and can lead to misleading or exaggerated conclusions.\nIn most cases, the more conservative two-sided test is recommended.\n\n### How to use a one-sided t-test\n\nTo perform a one-sided t-test, you need to specify the alternative hypothesis in the `alternative` argument in the `t.test()` function.\nThe following code shows how to perform the same one-sample t-test as above, but this time as a one-sided test.\nWe'll test if the mean number of hours spent consuming news is significantly greater than 14 hours.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(news_consumption ~ 1, mu = 14, data = d, alternative = \"greater\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  news_consumption\nt = 1.7229, df = 599, p-value = 0.04271\nalternative hypothesis: true mean is greater than 14\n95 percent confidence interval:\n 14.01124      Inf\nsample estimates:\nmean of x \n 14.25667 \n```\n\n\n:::\n:::\n\n\n\n\nWhen we tested this with a two-sided test, we found that the mean number of hours spent consuming news was not significantly *different* from 14 hours based on a $95%$ confidence level.\nBut with a one-sided test, we find that the mean number of hours spent consuming news is significantly *greater* than 14 hours.\nAlso note that the confidence interval is now one-sided, which you can see by the upper bound being `Inf` (infite).\nNote that in this case the use of a one-sided test is clearly not justified (see the word of caution above).\nThis is purely to demonstrate how using a one-sided test affects the p-value.\n\nSimilarly, we could test whether the mean number of hours spent consuming news is significantly *less* than 14 hours by setting `alternative = \"less\"`.\nWe'll skip the output here, but you can run it yourself to verify that this test is not significant. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(news_consumption ~ 1, mu = 14, data = d, alternative = \"less\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  news_consumption\nt = 1.7229, df = 599, p-value = 0.9573\nalternative hypothesis: true mean is less than 14\n95 percent confidence interval:\n     -Inf 14.50209\nsample estimates:\nmean of x \n 14.25667 \n```\n\n\n:::\n:::\n\n\n\n\n### one-sided test in independent and paired samples t-test\n\nIn the independent samples t-test and paired samples t-test you can specify the alternative hypothesis in the same way as in the one-sample t-test.\n\n* In the independent samples t-test, you can test if the mean of the first group is significantly *greater* or *less* than the mean of the second group.\n* In the paired samples t-test, you can test if the mean difference is significantly *greater* or *less* than zero. Be carefull (!!) that this difference is calculated as `trust_t1 - trust_t2`, so a positive difference means that the `trust_t1` is **greater** than `trust_t2`. In other words, if you test `alternative = \"greater\"`, you are testing if trust **decreased**.\n",
    "supporting": [
      "t-test_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}