<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ANOVA – Communication Science R Book</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../good-to-know/function-documentation.html" rel="next">
<link href="../../analysis/tests/linear-regression.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-34f2f06d33e71b70b9871a5af9c4576e.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="../../site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="../../site_libs/pagedtable-1.1/js/pagedtable.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../analysis/index.html">Analysis</a></li><li class="breadcrumb-item"><a href="../../analysis/tests/index.html">Statistical tests</a></li><li class="breadcrumb-item"><a href="../../analysis/tests/anova.html">ANOVA</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="https://vu.nl/en/about-vu/faculties/faculty-of-social-sciences/departments/communication-science" class="sidebar-logo-link">
      <img src="../../data/logo.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Communication Science R Book</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../getting-started/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Getting Started</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../getting-started/install-r-and-rstudio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Install R and RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../getting-started/using-rstudio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">How to use RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../getting-started/names-and-objects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Names and Objects</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../getting-started/types-of-objects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Types of Objects</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../getting-started/functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../getting-started/packages.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Packages</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../getting-started/file-management.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">File management</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../getting-started/working-in-quarto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Working in Quarto</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../data-management/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data management</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../data-management/the-tidyverse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The tidyverse</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../data-management/read-and-write.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Read and write</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../data-management/select-and-rename.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Select and rename</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../data-management/filter-and-arrange.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Filter and Arrange</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../data-management/mutate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mutate and recode</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../data-management/pipes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Using the pipe syntax</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../analysis/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../analysis/concepts/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Key concepts</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../analysis/concepts/hypotheses.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hypotheses</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../analysis/concepts/covariance-and-correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Covariance and correlation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../analysis/concepts/causality.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Causality</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../analysis/techniques/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Techniques</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../analysis/techniques/data-cleaning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data cleaning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../analysis/techniques/scale-construction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Scale construction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../analysis/techniques/factor-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Factor Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../analysis/techniques/controlling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Controlling for confounders</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../analysis/techniques/mediation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mediation Analyses</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../analysis/techniques/standardization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Standardization</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../analysis/tests/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistical tests</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth2 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../analysis/tests/t-test.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">The t-test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../analysis/tests/correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Correlation test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../analysis/tests/linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../analysis/tests/anova.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">ANOVA</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false">
 <span class="menu-text">Good to Know</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../good-to-know/function-documentation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Function Documentation</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#what-is-an-anova" id="toc-what-is-an-anova" class="nav-link active" data-scroll-target="#what-is-an-anova">What is an ANOVA?</a>
  <ul class="collapse">
  <li><a href="#one-way-anova" id="toc-one-way-anova" class="nav-link" data-scroll-target="#one-way-anova">One-way ANOVA</a></li>
  <li><a href="#two-way-anova" id="toc-two-way-anova" class="nav-link" data-scroll-target="#two-way-anova">Two-way ANOVA</a></li>
  <li><a href="#repeated-measures-anova" id="toc-repeated-measures-anova" class="nav-link" data-scroll-target="#repeated-measures-anova">Repeated measures ANOVA</a></li>
  <li><a href="#mixed-design-anova" id="toc-mixed-design-anova" class="nav-link" data-scroll-target="#mixed-design-anova">Mixed-design ANOVA</a></li>
  </ul></li>
  <li><a href="#how-to-use-it" id="toc-how-to-use-it" class="nav-link" data-scroll-target="#how-to-use-it">How to use it</a>
  <ul class="collapse">
  <li><a href="#one-way-anova-1" id="toc-one-way-anova-1" class="nav-link" data-scroll-target="#one-way-anova-1">One-way ANOVA</a>
  <ul class="collapse">
  <li><a href="#experimental-versus-observed-factors" id="toc-experimental-versus-observed-factors" class="nav-link" data-scroll-target="#experimental-versus-observed-factors"><em>Experimental</em> versus <em>observed</em> factors</a></li>
  </ul></li>
  <li><a href="#two-way-anova-1" id="toc-two-way-anova-1" class="nav-link" data-scroll-target="#two-way-anova-1">Two-way ANOVA</a></li>
  </ul></li>
  <li><a href="#conditions-and-assumptions" id="toc-conditions-and-assumptions" class="nav-link" data-scroll-target="#conditions-and-assumptions">Conditions and assumptions</a>
  <ul class="collapse">
  <li><a href="#homogeneity-of-variance" id="toc-homogeneity-of-variance" class="nav-link" data-scroll-target="#homogeneity-of-variance">Homogeneity of variance</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../analysis/index.html">Analysis</a></li><li class="breadcrumb-item"><a href="../../analysis/tests/index.html">Statistical tests</a></li><li class="breadcrumb-item"><a href="../../analysis/tests/anova.html">ANOVA</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">ANOVA</h1>
<p class="subtitle lead">Analysis of variance</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="what-is-an-anova" class="level1">
<h1>What is an ANOVA?</h1>
<p>Analysis of Variance, or ANOVA, is a statistical technique used to compare the means of several groups at once. ANOVA tests whether any of the group means differ more than would be expected by random variation alone. This makes it particularly suitable for experimental research, where participants are randomly assigned to different groups, and the researcher wants to know whether the groups differ on some outcome variable. Because of the random assignment, all possible confounding variables should be equally distributed over the groups, which allows us to make causal inferences about the effect of the independent variable on the dependent variable.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p>There are different types of ANOVA to cover a wide range of research designs. The most common ones are:</p>
<section id="one-way-anova" class="level3">
<h3 class="anchored" data-anchor-id="one-way-anova">One-way ANOVA</h3>
<ul>
<li><strong>Purpose</strong>. Compare means <em>between-subjects</em> in different groups.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></li>
<li><strong>Example</strong>. We want to know how the design of a health care robot affects how <em>comfortable</em> people feel about interacting with the robot. To test this we <em>randomly</em> asign participants to three experimental groups, that are shown three different robot designs (<a href="https://vu.nl/nl/onderzoek/meer-over/sociale-robots-voor-de-samenleving-mediapsychologie">Alice, Nao</a>, and RoboCop). They then answer multiple questions based on which we measure a <em>comfort rating</em> <a href="../../analysis/techniques/scale-construction.html">scale</a>. We can now use One-way ANOVA to compare the mean comfort rating between the three groups.</li>
</ul>
</section>
<section id="two-way-anova" class="level3">
<h3 class="anchored" data-anchor-id="two-way-anova">Two-way ANOVA</h3>
<ul>
<li><strong>Purpose</strong>. Compare means <em>between-subjects</em> in different groups, for two independent variables.</li>
<li><strong>Example</strong>. In addition to comparing three different designs of a health care robot, we could also compare between using a <em>male</em> or <em>female</em> voice. We then randomly assign participants to six groups (3 designs * 2 voices), and use two-way ANOVA to test whether the design and voice have an effect on the perceived attractiveness. We can then also test whether there is an <em>interaction</em> between the two variables, to see if specific combinations of design and voice are particularly comforting.</li>
</ul>
</section>
<section id="repeated-measures-anova" class="level3">
<h3 class="anchored" data-anchor-id="repeated-measures-anova">Repeated measures ANOVA</h3>
<ul>
<li><strong>Purpose</strong>. Compare means <em>within-subjects</em> measured at different timepoints.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></li>
<li><strong>Example</strong>. Instead of the self-reporting comfort rating, we could measure how people react to interacting with a health care robot by measuring their <em>heart rate</em>. We could then measure the <em>heart rate</em> of participants <em>before</em>, <em>during</em>, and <em>after</em> interacting with the robot. We can then use repeated measures ANOVA to compare the <em>heart rate</em> at each stage.</li>
</ul>
</section>
<section id="mixed-design-anova" class="level3">
<h3 class="anchored" data-anchor-id="mixed-design-anova">Mixed-design ANOVA</h3>
<ul>
<li><strong>Purpose</strong>. Combine <em>between-subjects</em> and <em>within-subjects</em> factors.</li>
<li><strong>Example</strong>. This allows us to measure simultaneously the effect of the design of a health care robot (one-way anova example) on the change in <em>heart rate</em> (repeated measures example). We divide participants into three groups that are shown the three different designs, and measure the <em>heart rate</em> of participants <em>before</em>, <em>during</em>, and <em>after</em> interacting with the robot. We can then use mixed-design ANOVA to test whether the three designs of a health care robot affect the change in hearthrate differently.</li>
</ul>
<!-- # How does it work

Underneath the hood, ANOVA is a linear model just like [regression analysis](../tests/linear-regression.qmd).
If you have not yet read the regression tutorial, you can skip this section, and focus first on how to use ANOVA in practice.

You can think of ANOVA as a special case of regression where the independent variables are categorical.
In the regression tutorial we showed you how you can use categorical independent variables in a regression model using dummy variables.
You might recall that it's not straightforward to compare all of the groups, or to test overall whether there is a difference between the groups.
ANOVA is a more specialized tool for this purpose.

To understand how ANOVA is *different* from *regular regression*, you need to understand two concepts.[^not_different]

[^not_different]: We emphasize *different* and *regular regression*, because technically ANOVA is still just a type of regression. By different we here refer to how ANOVA and regression are most commonly used in our field.

* **Contrast coding**. In regression we usually use **dummy coding** for categorical variables, which compares each group to a single reference group. But we can also use **effect coding** to compare each group to the *grand mean* (the mean of all groups). 
* **Sum of squares**. In a linear model we use sum of squares to assess how much variance is explained by the model. ANOVA allows using different types of sum of squares (Type I, II, III) for different purposes. In most cases researchers use Type III sums of squares (which is the default in popular statistics software like SPSS).



In the social sciences, when researchers use ANOVA, they usually use Type III sums of squares and effect coding. In popular statistics software like SPSS, this is also the default approach.
In this tutorial we will also stick to this default.
But as you'll see in the code, we do need to specify ourselves that we want to use Type II sums of squares and effect coding (specifically we'll use Helmert coding). -->
</section>
</section>
<section id="how-to-use-it" class="level1">
<h1>How to use it</h1>
<p>We’ll use the <code>afex</code> and <code>emmeans</code> packages to perform ANOVA tests and compare means, and we’ll use the <code>sjPlot</code> package to visualize the results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(afex)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>For our examples we’ll use our <a href="../../data-management/index.html#practice-data">Practice data</a>. In this data have a (fictional) experiment where we study the effect of popular media on people’s trust in journalists. Specifically, we’re using the following variables:</p>
<ul>
<li><strong>id</strong>. A unique identifier for each participant.</li>
<li><strong>experiment_group</strong>. The group that participants were assigned to. Each group viewed a different movie that was either <em>neutral</em> (control), <em>positive</em>, or <em>negative</em> about journalism.</li>
<li><strong>np_subscription</strong>. Whether participants have a subscription to a national newspaper, with values <em>yes</em> or <em>no</em>.</li>
<li><strong>trust_t1</strong> and <strong>trust_t2</strong>. The trust in journalists, measured before (t1) and after (t2) watching a movie about journalism.</li>
</ul>
<p>The <strong>experiment_group</strong> and <strong>np_subscription</strong> variables are our independent variable. To use these in the ANOVA, we’ll explicitly convert them to factors, to indicate that they are categorical variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://dataliteracy.cc/data/practice_data.csv"</span>) <span class="sc">|&gt;</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>        <span class="fu">mutate</span>(<span class="at">experiment_group =</span> <span class="fu">as.factor</span>(experiment_group),</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">np_subscription =</span> <span class="fu">as.factor</span>(np_subscription)) <span class="sc">|&gt;</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>        <span class="fu">select</span>(id, experiment_group, np_subscription, trust_t1, trust_t2)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>d</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["id"],"name":[1],"type":["dbl"],"align":["right"]},{"label":["experiment_group"],"name":[2],"type":["fct"],"align":["left"]},{"label":["np_subscription"],"name":[3],"type":["fct"],"align":["left"]},{"label":["trust_t1"],"name":[4],"type":["dbl"],"align":["right"]},{"label":["trust_t2"],"name":[5],"type":["dbl"],"align":["right"]}],"data":[{"1":"1","2":"control","3":"no","4":"2.50","5":"2.00"},{"1":"2","2":"control","3":"yes","4":"4.00","5":"4.00"},{"1":"3","2":"negative","3":"no","4":"3.00","5":"1.00"},{"1":"4","2":"negative","3":"no","4":"3.75","5":"1.75"},{"1":"5","2":"control","3":"no","4":"6.00","5":"6.25"},{"1":"6","2":"control","3":"yes","4":"5.50","5":"7.00"},{"1":"7","2":"negative","3":"no","4":"4.00","5":"3.75"},{"1":"8","2":"control","3":"yes","4":"5.50","5":"5.25"},{"1":"9","2":"positive","3":"yes","4":"6.75","5":"6.75"},{"1":"10","2":"control","3":"yes","4":"4.75","5":"3.75"},{"1":"11","2":"positive","3":"no","4":"3.50","5":"5.00"},{"1":"12","2":"negative","3":"yes","4":"4.25","5":"3.25"},{"1":"13","2":"negative","3":"no","4":"3.25","5":"2.50"},{"1":"14","2":"positive","3":"no","4":"3.50","5":"4.50"},{"1":"15","2":"negative","3":"yes","4":"5.00","5":"4.25"},{"1":"16","2":"negative","3":"no","4":"2.75","5":"2.50"},{"1":"17","2":"control","3":"yes","4":"5.25","5":"6.75"},{"1":"18","2":"control","3":"yes","4":"5.00","5":"3.75"},{"1":"19","2":"positive","3":"no","4":"4.50","5":"6.25"},{"1":"20","2":"positive","3":"yes","4":"5.00","5":"5.25"},{"1":"21","2":"control","3":"yes","4":"6.50","5":"6.25"},{"1":"22","2":"control","3":"yes","4":"3.75","5":"4.25"},{"1":"23","2":"positive","3":"yes","4":"4.25","5":"2.75"},{"1":"24","2":"control","3":"no","4":"3.25","5":"3.50"},{"1":"25","2":"negative","3":"no","4":"5.50","5":"4.25"},{"1":"26","2":"positive","3":"yes","4":"1.50","5":"3.50"},{"1":"27","2":"negative","3":"yes","4":"5.25","5":"5.25"},{"1":"28","2":"negative","3":"no","4":"5.00","5":"5.00"},{"1":"29","2":"control","3":"yes","4":"4.25","5":"3.50"},{"1":"30","2":"positive","3":"no","4":"3.50","5":"4.50"},{"1":"31","2":"positive","3":"no","4":"4.25","5":"4.75"},{"1":"32","2":"positive","3":"yes","4":"5.25","5":"6.50"},{"1":"33","2":"positive","3":"yes","4":"6.00","5":"5.75"},{"1":"34","2":"control","3":"yes","4":"4.75","5":"6.25"},{"1":"35","2":"positive","3":"no","4":"5.50","5":"5.25"},{"1":"36","2":"negative","3":"yes","4":"4.50","5":"5.00"},{"1":"37","2":"negative","3":"yes","4":"5.00","5":"5.75"},{"1":"38","2":"control","3":"yes","4":"5.25","5":"5.00"},{"1":"39","2":"positive","3":"yes","4":"3.50","5":"3.00"},{"1":"40","2":"negative","3":"yes","4":"1.25","5":"2.00"},{"1":"41","2":"negative","3":"no","4":"2.50","5":"2.50"},{"1":"42","2":"control","3":"no","4":"2.25","5":"3.00"},{"1":"43","2":"negative","3":"yes","4":"4.50","5":"4.00"},{"1":"44","2":"positive","3":"no","4":"2.75","5":"3.75"},{"1":"45","2":"control","3":"yes","4":"4.75","5":"6.50"},{"1":"46","2":"negative","3":"no","4":"4.25","5":"3.00"},{"1":"47","2":"negative","3":"yes","4":"3.75","5":"3.00"},{"1":"48","2":"control","3":"yes","4":"4.00","5":"5.00"},{"1":"49","2":"control","3":"yes","4":"3.75","5":"3.50"},{"1":"50","2":"negative","3":"no","4":"4.00","5":"2.00"},{"1":"51","2":"positive","3":"no","4":"6.00","5":"8.00"},{"1":"52","2":"positive","3":"no","4":"4.25","5":"6.00"},{"1":"53","2":"negative","3":"yes","4":"3.75","5":"1.00"},{"1":"54","2":"control","3":"yes","4":"5.50","5":"6.00"},{"1":"55","2":"positive","3":"no","4":"5.25","5":"7.00"},{"1":"56","2":"control","3":"no","4":"3.25","5":"4.00"},{"1":"57","2":"negative","3":"no","4":"3.25","5":"3.75"},{"1":"58","2":"negative","3":"yes","4":"3.50","5":"4.50"},{"1":"59","2":"positive","3":"yes","4":"3.25","5":"2.50"},{"1":"60","2":"negative","3":"no","4":"5.50","5":"3.75"},{"1":"61","2":"control","3":"yes","4":"4.75","5":"5.25"},{"1":"62","2":"positive","3":"yes","4":"4.00","5":"2.75"},{"1":"63","2":"control","3":"no","4":"4.75","5":"4.50"},{"1":"64","2":"negative","3":"yes","4":"4.75","5":"4.50"},{"1":"65","2":"control","3":"no","4":"4.75","5":"6.50"},{"1":"66","2":"positive","3":"yes","4":"4.00","5":"3.75"},{"1":"67","2":"positive","3":"yes","4":"5.25","5":"4.75"},{"1":"68","2":"negative","3":"yes","4":"5.00","5":"5.00"},{"1":"69","2":"control","3":"no","4":"3.75","5":"4.75"},{"1":"70","2":"negative","3":"no","4":"4.25","5":"1.75"},{"1":"71","2":"negative","3":"yes","4":"5.75","5":"5.25"},{"1":"72","2":"positive","3":"yes","4":"2.25","5":"3.50"},{"1":"73","2":"positive","3":"yes","4":"4.50","5":"5.25"},{"1":"74","2":"positive","3":"yes","4":"5.50","5":"4.50"},{"1":"75","2":"negative","3":"yes","4":"3.75","5":"2.00"},{"1":"76","2":"negative","3":"yes","4":"3.50","5":"3.00"},{"1":"77","2":"positive","3":"yes","4":"4.00","5":"4.50"},{"1":"78","2":"control","3":"yes","4":"4.75","5":"6.50"},{"1":"79","2":"positive","3":"yes","4":"5.50","5":"6.75"},{"1":"80","2":"positive","3":"yes","4":"4.75","5":"4.25"},{"1":"81","2":"positive","3":"no","4":"4.50","5":"4.75"},{"1":"82","2":"control","3":"yes","4":"5.00","5":"6.25"},{"1":"83","2":"control","3":"no","4":"3.25","5":"5.25"},{"1":"84","2":"negative","3":"no","4":"3.50","5":"3.75"},{"1":"85","2":"negative","3":"no","4":"3.75","5":"4.00"},{"1":"86","2":"positive","3":"no","4":"5.25","5":"6.00"},{"1":"87","2":"positive","3":"yes","4":"5.00","5":"5.50"},{"1":"88","2":"negative","3":"no","4":"6.50","5":"6.00"},{"1":"89","2":"negative","3":"no","4":"5.50","5":"4.50"},{"1":"90","2":"positive","3":"yes","4":"4.25","5":"3.00"},{"1":"91","2":"negative","3":"yes","4":"4.00","5":"4.50"},{"1":"92","2":"control","3":"no","4":"5.25","5":"4.75"},{"1":"93","2":"negative","3":"no","4":"5.50","5":"4.00"},{"1":"94","2":"negative","3":"no","4":"4.00","5":"2.25"},{"1":"95","2":"control","3":"yes","4":"5.25","5":"7.00"},{"1":"96","2":"positive","3":"no","4":"4.25","5":"4.75"},{"1":"97","2":"control","3":"yes","4":"4.25","5":"4.25"},{"1":"98","2":"positive","3":"yes","4":"5.25","5":"7.75"},{"1":"99","2":"positive","3":"no","4":"5.00","5":"5.25"},{"1":"100","2":"negative","3":"yes","4":"4.50","5":"3.25"},{"1":"101","2":"control","3":"no","4":"5.25","5":"5.00"},{"1":"102","2":"negative","3":"no","4":"4.25","5":"2.25"},{"1":"103","2":"negative","3":"yes","4":"3.00","5":"3.25"},{"1":"104","2":"positive","3":"yes","4":"5.50","5":"7.50"},{"1":"105","2":"control","3":"no","4":"3.75","5":"3.50"},{"1":"106","2":"control","3":"yes","4":"3.75","5":"5.25"},{"1":"107","2":"positive","3":"no","4":"3.00","5":"4.50"},{"1":"108","2":"negative","3":"yes","4":"3.75","5":"3.00"},{"1":"109","2":"negative","3":"yes","4":"4.25","5":"2.75"},{"1":"110","2":"negative","3":"yes","4":"4.25","5":"4.50"},{"1":"111","2":"control","3":"no","4":"5.50","5":"6.75"},{"1":"112","2":"negative","3":"no","4":"3.25","5":"1.75"},{"1":"113","2":"negative","3":"no","4":"4.50","5":"1.50"},{"1":"114","2":"negative","3":"no","4":"4.25","5":"3.25"},{"1":"115","2":"positive","3":"yes","4":"5.00","5":"5.50"},{"1":"116","2":"negative","3":"yes","4":"4.00","5":"3.75"},{"1":"117","2":"negative","3":"no","4":"4.25","5":"3.50"},{"1":"118","2":"negative","3":"yes","4":"3.75","5":"3.00"},{"1":"119","2":"negative","3":"yes","4":"4.00","5":"3.75"},{"1":"120","2":"positive","3":"no","4":"2.50","5":"3.25"},{"1":"121","2":"positive","3":"no","4":"4.50","5":"3.50"},{"1":"122","2":"control","3":"yes","4":"4.25","5":"5.25"},{"1":"123","2":"control","3":"no","4":"4.25","5":"4.25"},{"1":"124","2":"positive","3":"yes","4":"4.50","5":"5.25"},{"1":"125","2":"control","3":"yes","4":"4.25","5":"5.00"},{"1":"126","2":"negative","3":"yes","4":"4.50","5":"3.25"},{"1":"127","2":"negative","3":"yes","4":"4.00","5":"3.25"},{"1":"128","2":"control","3":"yes","4":"4.00","5":"5.75"},{"1":"129","2":"negative","3":"no","4":"3.00","5":"2.00"},{"1":"130","2":"positive","3":"no","4":"3.25","5":"2.25"},{"1":"131","2":"control","3":"yes","4":"4.50","5":"4.25"},{"1":"132","2":"positive","3":"no","4":"3.00","5":"4.00"},{"1":"133","2":"negative","3":"yes","4":"3.50","5":"3.75"},{"1":"134","2":"positive","3":"yes","4":"2.75","5":"3.50"},{"1":"135","2":"positive","3":"no","4":"3.75","5":"6.00"},{"1":"136","2":"control","3":"yes","4":"5.25","5":"6.00"},{"1":"137","2":"control","3":"no","4":"4.75","5":"7.00"},{"1":"138","2":"negative","3":"yes","4":"2.25","5":"2.25"},{"1":"139","2":"control","3":"yes","4":"5.50","5":"7.50"},{"1":"140","2":"positive","3":"no","4":"5.00","5":"5.00"},{"1":"141","2":"negative","3":"yes","4":"3.75","5":"4.75"},{"1":"142","2":"positive","3":"yes","4":"5.50","5":"5.25"},{"1":"143","2":"negative","3":"no","4":"3.50","5":"1.00"},{"1":"144","2":"control","3":"no","4":"4.75","5":"4.00"},{"1":"145","2":"control","3":"yes","4":"4.25","5":"3.75"},{"1":"146","2":"control","3":"yes","4":"4.00","5":"3.75"},{"1":"147","2":"negative","3":"no","4":"5.00","5":"3.00"},{"1":"148","2":"control","3":"yes","4":"4.25","5":"3.75"},{"1":"149","2":"positive","3":"no","4":"5.00","5":"5.75"},{"1":"150","2":"positive","3":"no","4":"5.75","5":"5.00"},{"1":"151","2":"positive","3":"no","4":"5.50","5":"5.25"},{"1":"152","2":"negative","3":"yes","4":"4.25","5":"4.50"},{"1":"153","2":"positive","3":"no","4":"2.50","5":"4.75"},{"1":"154","2":"positive","3":"yes","4":"3.00","5":"3.50"},{"1":"155","2":"control","3":"no","4":"4.50","5":"5.50"},{"1":"156","2":"control","3":"yes","4":"4.75","5":"5.25"},{"1":"157","2":"positive","3":"yes","4":"3.50","5":"4.00"},{"1":"158","2":"control","3":"yes","4":"4.50","5":"4.50"},{"1":"159","2":"control","3":"no","4":"5.25","5":"3.75"},{"1":"160","2":"positive","3":"no","4":"5.00","5":"5.75"},{"1":"161","2":"positive","3":"no","4":"3.50","5":"2.75"},{"1":"162","2":"positive","3":"yes","4":"7.75","5":"8.00"},{"1":"163","2":"positive","3":"no","4":"2.25","5":"4.00"},{"1":"164","2":"positive","3":"no","4":"2.00","5":"2.50"},{"1":"165","2":"control","3":"yes","4":"4.75","5":"5.25"},{"1":"166","2":"negative","3":"yes","4":"5.00","5":"5.25"},{"1":"167","2":"negative","3":"no","4":"3.50","5":"2.50"},{"1":"168","2":"negative","3":"no","4":"2.75","5":"1.00"},{"1":"169","2":"positive","3":"yes","4":"5.00","5":"4.75"},{"1":"170","2":"control","3":"yes","4":"5.25","5":"6.25"},{"1":"171","2":"positive","3":"yes","4":"6.25","5":"5.25"},{"1":"172","2":"control","3":"yes","4":"4.25","5":"4.25"},{"1":"173","2":"positive","3":"no","4":"3.50","5":"4.25"},{"1":"174","2":"positive","3":"no","4":"4.25","5":"4.25"},{"1":"175","2":"control","3":"yes","4":"6.00","5":"7.00"},{"1":"176","2":"positive","3":"no","4":"2.75","5":"3.00"},{"1":"177","2":"control","3":"no","4":"4.00","5":"4.75"},{"1":"178","2":"positive","3":"yes","4":"3.25","5":"4.00"},{"1":"179","2":"negative","3":"no","4":"2.25","5":"1.00"},{"1":"180","2":"positive","3":"yes","4":"3.00","5":"3.25"},{"1":"181","2":"negative","3":"no","4":"5.50","5":"2.25"},{"1":"182","2":"negative","3":"yes","4":"6.00","5":"5.00"},{"1":"183","2":"control","3":"no","4":"3.25","5":"2.75"},{"1":"184","2":"negative","3":"yes","4":"5.25","5":"5.50"},{"1":"185","2":"negative","3":"yes","4":"4.75","5":"3.50"},{"1":"186","2":"control","3":"no","4":"4.00","5":"3.50"},{"1":"187","2":"control","3":"yes","4":"4.50","5":"4.75"},{"1":"188","2":"control","3":"no","4":"4.75","5":"3.25"},{"1":"189","2":"positive","3":"no","4":"4.00","5":"4.75"},{"1":"190","2":"control","3":"no","4":"4.50","5":"3.25"},{"1":"191","2":"control","3":"yes","4":"3.50","5":"3.50"},{"1":"192","2":"positive","3":"yes","4":"5.75","5":"6.25"},{"1":"193","2":"negative","3":"no","4":"3.25","5":"2.50"},{"1":"194","2":"negative","3":"no","4":"5.50","5":"2.50"},{"1":"195","2":"positive","3":"yes","4":"2.25","5":"1.50"},{"1":"196","2":"negative","3":"no","4":"3.50","5":"1.50"},{"1":"197","2":"control","3":"yes","4":"3.75","5":"3.00"},{"1":"198","2":"positive","3":"yes","4":"6.00","5":"7.25"},{"1":"199","2":"control","3":"yes","4":"4.75","5":"4.75"},{"1":"200","2":"control","3":"yes","4":"6.50","5":"6.00"},{"1":"201","2":"positive","3":"yes","4":"4.50","5":"3.75"},{"1":"202","2":"negative","3":"no","4":"5.25","5":"3.75"},{"1":"203","2":"negative","3":"yes","4":"3.75","5":"3.25"},{"1":"204","2":"control","3":"no","4":"2.75","5":"2.00"},{"1":"205","2":"negative","3":"yes","4":"4.00","5":"5.50"},{"1":"206","2":"positive","3":"yes","4":"5.25","5":"5.50"},{"1":"207","2":"negative","3":"yes","4":"3.75","5":"1.50"},{"1":"208","2":"positive","3":"no","4":"4.75","5":"5.75"},{"1":"209","2":"positive","3":"no","4":"5.50","5":"6.50"},{"1":"210","2":"positive","3":"yes","4":"2.75","5":"4.25"},{"1":"211","2":"negative","3":"yes","4":"5.50","5":"5.00"},{"1":"212","2":"positive","3":"no","4":"3.25","5":"3.50"},{"1":"213","2":"negative","3":"no","4":"4.25","5":"3.50"},{"1":"214","2":"negative","3":"no","4":"4.25","5":"3.75"},{"1":"215","2":"control","3":"yes","4":"5.25","5":"6.25"},{"1":"216","2":"negative","3":"yes","4":"4.50","5":"4.00"},{"1":"217","2":"control","3":"no","4":"3.50","5":"2.50"},{"1":"218","2":"positive","3":"yes","4":"4.25","5":"4.00"},{"1":"219","2":"negative","3":"no","4":"5.50","5":"6.00"},{"1":"220","2":"negative","3":"no","4":"3.50","5":"3.25"},{"1":"221","2":"negative","3":"yes","4":"4.75","5":"5.50"},{"1":"222","2":"positive","3":"yes","4":"3.75","5":"4.25"},{"1":"223","2":"negative","3":"yes","4":"5.25","5":"5.50"},{"1":"224","2":"negative","3":"no","4":"4.00","5":"3.00"},{"1":"225","2":"positive","3":"yes","4":"4.75","5":"5.50"},{"1":"226","2":"positive","3":"yes","4":"4.00","5":"3.50"},{"1":"227","2":"control","3":"yes","4":"2.25","5":"1.25"},{"1":"228","2":"positive","3":"no","4":"7.25","5":"8.50"},{"1":"229","2":"control","3":"no","4":"3.50","5":"3.75"},{"1":"230","2":"positive","3":"yes","4":"3.50","5":"4.00"},{"1":"231","2":"control","3":"yes","4":"4.25","5":"5.00"},{"1":"232","2":"positive","3":"yes","4":"4.00","5":"6.25"},{"1":"233","2":"positive","3":"yes","4":"3.75","5":"5.50"},{"1":"234","2":"positive","3":"no","4":"4.25","5":"5.25"},{"1":"235","2":"negative","3":"yes","4":"5.00","5":"4.75"},{"1":"236","2":"control","3":"yes","4":"6.00","5":"5.25"},{"1":"237","2":"control","3":"yes","4":"6.25","5":"7.50"},{"1":"238","2":"positive","3":"yes","4":"4.25","5":"4.25"},{"1":"239","2":"control","3":"yes","4":"4.50","5":"6.00"},{"1":"240","2":"control","3":"no","4":"4.00","5":"3.75"},{"1":"241","2":"positive","3":"no","4":"5.50","5":"5.00"},{"1":"242","2":"control","3":"no","4":"2.50","5":"1.50"},{"1":"243","2":"control","3":"no","4":"5.75","5":"6.00"},{"1":"244","2":"positive","3":"no","4":"5.25","5":"4.25"},{"1":"245","2":"positive","3":"yes","4":"4.75","5":"6.75"},{"1":"246","2":"negative","3":"no","4":"2.50","5":"1.75"},{"1":"247","2":"negative","3":"no","4":"2.50","5":"1.00"},{"1":"248","2":"negative","3":"yes","4":"5.25","5":"2.50"},{"1":"249","2":"control","3":"yes","4":"5.25","5":"4.25"},{"1":"250","2":"positive","3":"no","4":"3.75","5":"4.25"},{"1":"251","2":"positive","3":"no","4":"4.75","5":"6.50"},{"1":"252","2":"positive","3":"yes","4":"4.50","5":"5.00"},{"1":"253","2":"negative","3":"no","4":"5.75","5":"4.25"},{"1":"254","2":"negative","3":"no","4":"4.50","5":"4.50"},{"1":"255","2":"positive","3":"yes","4":"4.50","5":"5.25"},{"1":"256","2":"positive","3":"yes","4":"4.50","5":"4.25"},{"1":"257","2":"negative","3":"yes","4":"5.75","5":"6.50"},{"1":"258","2":"positive","3":"no","4":"4.75","5":"2.50"},{"1":"259","2":"negative","3":"yes","4":"4.75","5":"5.00"},{"1":"260","2":"control","3":"no","4":"4.00","5":"4.50"},{"1":"261","2":"negative","3":"no","4":"3.50","5":"3.25"},{"1":"262","2":"positive","3":"yes","4":"6.00","5":"7.00"},{"1":"263","2":"positive","3":"yes","4":"5.50","5":"6.25"},{"1":"264","2":"positive","3":"yes","4":"5.50","5":"4.25"},{"1":"265","2":"control","3":"no","4":"4.25","5":"4.50"},{"1":"266","2":"control","3":"yes","4":"3.75","5":"4.50"},{"1":"267","2":"positive","3":"no","4":"3.75","5":"5.00"},{"1":"268","2":"negative","3":"no","4":"1.75","5":"1.00"},{"1":"269","2":"positive","3":"yes","4":"2.75","5":"1.50"},{"1":"270","2":"positive","3":"no","4":"4.50","5":"6.50"},{"1":"271","2":"negative","3":"no","4":"3.25","5":"1.00"},{"1":"272","2":"positive","3":"yes","4":"5.50","5":"7.00"},{"1":"273","2":"control","3":"no","4":"4.50","5":"4.50"},{"1":"274","2":"negative","3":"yes","4":"4.25","5":"2.75"},{"1":"275","2":"positive","3":"no","4":"4.25","5":"5.75"},{"1":"276","2":"positive","3":"yes","4":"4.50","5":"3.75"},{"1":"277","2":"control","3":"yes","4":"6.00","5":"6.25"},{"1":"278","2":"positive","3":"yes","4":"7.25","5":"7.50"},{"1":"279","2":"negative","3":"yes","4":"6.50","5":"7.50"},{"1":"280","2":"control","3":"no","4":"4.50","5":"4.50"},{"1":"281","2":"positive","3":"no","4":"5.00","5":"5.50"},{"1":"282","2":"control","3":"no","4":"4.00","5":"4.00"},{"1":"283","2":"control","3":"yes","4":"6.75","5":"6.25"},{"1":"284","2":"negative","3":"yes","4":"4.00","5":"4.50"},{"1":"285","2":"negative","3":"no","4":"3.25","5":"1.75"},{"1":"286","2":"positive","3":"no","4":"3.25","5":"4.50"},{"1":"287","2":"positive","3":"yes","4":"2.50","5":"3.00"},{"1":"288","2":"negative","3":"no","4":"3.00","5":"1.00"},{"1":"289","2":"negative","3":"no","4":"4.25","5":"3.25"},{"1":"290","2":"control","3":"yes","4":"4.50","5":"5.00"},{"1":"291","2":"control","3":"yes","4":"5.00","5":"4.00"},{"1":"292","2":"control","3":"yes","4":"5.50","5":"7.50"},{"1":"293","2":"control","3":"no","4":"5.75","5":"4.75"},{"1":"294","2":"control","3":"yes","4":"5.50","5":"3.75"},{"1":"295","2":"control","3":"yes","4":"5.25","5":"5.25"},{"1":"296","2":"negative","3":"no","4":"5.25","5":"4.50"},{"1":"297","2":"negative","3":"no","4":"2.75","5":"1.25"},{"1":"298","2":"control","3":"yes","4":"3.50","5":"4.50"},{"1":"299","2":"control","3":"no","4":"5.50","5":"7.50"},{"1":"300","2":"negative","3":"no","4":"4.25","5":"3.25"},{"1":"301","2":"control","3":"no","4":"3.00","5":"2.25"},{"1":"302","2":"negative","3":"yes","4":"5.50","5":"6.00"},{"1":"303","2":"control","3":"yes","4":"3.75","5":"2.75"},{"1":"304","2":"negative","3":"no","4":"6.00","5":"5.50"},{"1":"305","2":"control","3":"no","4":"3.25","5":"2.50"},{"1":"306","2":"control","3":"no","4":"4.25","5":"3.00"},{"1":"307","2":"negative","3":"yes","4":"4.75","5":"6.25"},{"1":"308","2":"negative","3":"no","4":"3.75","5":"3.25"},{"1":"309","2":"positive","3":"no","4":"2.50","5":"1.75"},{"1":"310","2":"control","3":"yes","4":"5.25","5":"5.00"},{"1":"311","2":"control","3":"yes","4":"3.75","5":"4.50"},{"1":"312","2":"control","3":"yes","4":"5.00","5":"6.25"},{"1":"313","2":"control","3":"no","4":"3.25","5":"3.50"},{"1":"314","2":"negative","3":"no","4":"3.00","5":"1.25"},{"1":"315","2":"control","3":"yes","4":"5.00","5":"5.25"},{"1":"316","2":"positive","3":"no","4":"4.50","5":"5.75"},{"1":"317","2":"control","3":"yes","4":"4.75","5":"4.25"},{"1":"318","2":"negative","3":"no","4":"4.50","5":"2.00"},{"1":"319","2":"positive","3":"yes","4":"3.25","5":"4.00"},{"1":"320","2":"negative","3":"yes","4":"5.00","5":"4.25"},{"1":"321","2":"control","3":"yes","4":"4.25","5":"3.75"},{"1":"322","2":"negative","3":"yes","4":"5.75","5":"4.75"},{"1":"323","2":"positive","3":"no","4":"3.75","5":"5.00"},{"1":"324","2":"positive","3":"no","4":"4.25","5":"4.50"},{"1":"325","2":"negative","3":"yes","4":"4.25","5":"4.00"},{"1":"326","2":"control","3":"no","4":"4.25","5":"4.50"},{"1":"327","2":"control","3":"yes","4":"5.75","5":"5.25"},{"1":"328","2":"control","3":"yes","4":"4.25","5":"4.75"},{"1":"329","2":"control","3":"yes","4":"6.75","5":"8.00"},{"1":"330","2":"control","3":"yes","4":"4.00","5":"4.25"},{"1":"331","2":"negative","3":"no","4":"4.00","5":"3.25"},{"1":"332","2":"positive","3":"no","4":"6.75","5":"7.00"},{"1":"333","2":"positive","3":"yes","4":"2.00","5":"1.75"},{"1":"334","2":"control","3":"no","4":"2.50","5":"3.75"},{"1":"335","2":"positive","3":"yes","4":"6.50","5":"7.50"},{"1":"336","2":"negative","3":"no","4":"4.75","5":"4.00"},{"1":"337","2":"control","3":"yes","4":"5.50","5":"4.50"},{"1":"338","2":"negative","3":"yes","4":"4.75","5":"4.00"},{"1":"339","2":"control","3":"no","4":"3.50","5":"2.25"},{"1":"340","2":"negative","3":"yes","4":"4.25","5":"5.00"},{"1":"341","2":"control","3":"yes","4":"6.00","5":"5.50"},{"1":"342","2":"negative","3":"yes","4":"3.50","5":"2.75"},{"1":"343","2":"control","3":"no","4":"1.75","5":"1.50"},{"1":"344","2":"positive","3":"no","4":"5.75","5":"6.75"},{"1":"345","2":"negative","3":"yes","4":"7.00","5":"6.50"},{"1":"346","2":"positive","3":"no","4":"5.50","5":"6.00"},{"1":"347","2":"positive","3":"no","4":"3.25","5":"4.00"},{"1":"348","2":"control","3":"yes","4":"2.50","5":"1.50"},{"1":"349","2":"positive","3":"yes","4":"3.25","5":"5.00"},{"1":"350","2":"negative","3":"yes","4":"3.75","5":"5.00"},{"1":"351","2":"positive","3":"yes","4":"3.25","5":"4.75"},{"1":"352","2":"control","3":"yes","4":"5.50","5":"3.75"},{"1":"353","2":"negative","3":"yes","4":"4.75","5":"4.25"},{"1":"354","2":"control","3":"yes","4":"4.00","5":"6.25"},{"1":"355","2":"control","3":"no","4":"3.50","5":"3.00"},{"1":"356","2":"positive","3":"yes","4":"5.75","5":"7.00"},{"1":"357","2":"control","3":"no","4":"2.00","5":"1.25"},{"1":"358","2":"negative","3":"yes","4":"6.50","5":"6.25"},{"1":"359","2":"control","3":"yes","4":"4.50","5":"5.00"},{"1":"360","2":"control","3":"no","4":"4.25","5":"3.75"},{"1":"361","2":"positive","3":"no","4":"5.25","5":"5.50"},{"1":"362","2":"control","3":"yes","4":"4.50","5":"4.75"},{"1":"363","2":"negative","3":"no","4":"5.75","5":"2.50"},{"1":"364","2":"negative","3":"yes","4":"4.25","5":"5.50"},{"1":"365","2":"control","3":"yes","4":"5.00","5":"5.25"},{"1":"366","2":"negative","3":"no","4":"4.25","5":"4.00"},{"1":"367","2":"negative","3":"yes","4":"4.25","5":"3.25"},{"1":"368","2":"positive","3":"yes","4":"4.00","5":"4.75"},{"1":"369","2":"negative","3":"yes","4":"3.75","5":"5.75"},{"1":"370","2":"negative","3":"yes","4":"5.75","5":"5.00"},{"1":"371","2":"control","3":"no","4":"4.50","5":"5.00"},{"1":"372","2":"negative","3":"yes","4":"5.25","5":"7.50"},{"1":"373","2":"control","3":"yes","4":"3.50","5":"4.25"},{"1":"374","2":"negative","3":"yes","4":"6.00","5":"6.50"},{"1":"375","2":"positive","3":"no","4":"2.25","5":"2.00"},{"1":"376","2":"negative","3":"no","4":"4.50","5":"1.25"},{"1":"377","2":"negative","3":"no","4":"4.00","5":"1.25"},{"1":"378","2":"control","3":"no","4":"4.50","5":"5.00"},{"1":"379","2":"positive","3":"yes","4":"4.50","5":"3.75"},{"1":"380","2":"negative","3":"yes","4":"3.75","5":"3.75"},{"1":"381","2":"control","3":"yes","4":"4.25","5":"4.00"},{"1":"382","2":"positive","3":"no","4":"2.75","5":"1.75"},{"1":"383","2":"negative","3":"no","4":"3.75","5":"1.00"},{"1":"384","2":"control","3":"yes","4":"3.00","5":"3.25"},{"1":"385","2":"negative","3":"yes","4":"2.25","5":"2.00"},{"1":"386","2":"positive","3":"yes","4":"4.00","5":"6.25"},{"1":"387","2":"positive","3":"no","4":"5.00","5":"5.50"},{"1":"388","2":"positive","3":"no","4":"4.50","5":"6.25"},{"1":"389","2":"negative","3":"yes","4":"4.00","5":"3.75"},{"1":"390","2":"negative","3":"yes","4":"3.75","5":"4.25"},{"1":"391","2":"control","3":"no","4":"4.00","5":"3.75"},{"1":"392","2":"negative","3":"yes","4":"5.25","5":"5.50"},{"1":"393","2":"control","3":"yes","4":"3.75","5":"5.25"},{"1":"394","2":"positive","3":"no","4":"3.25","5":"3.75"},{"1":"395","2":"positive","3":"yes","4":"5.25","5":"4.75"},{"1":"396","2":"negative","3":"no","4":"3.25","5":"1.00"},{"1":"397","2":"negative","3":"no","4":"3.00","5":"1.50"},{"1":"398","2":"positive","3":"no","4":"3.75","5":"3.75"},{"1":"399","2":"positive","3":"yes","4":"5.50","5":"3.75"},{"1":"400","2":"positive","3":"yes","4":"3.75","5":"4.50"},{"1":"401","2":"negative","3":"yes","4":"4.50","5":"5.75"},{"1":"402","2":"control","3":"yes","4":"2.75","5":"3.00"},{"1":"403","2":"negative","3":"yes","4":"5.50","5":"4.25"},{"1":"404","2":"positive","3":"yes","4":"1.50","5":"2.25"},{"1":"405","2":"positive","3":"yes","4":"3.75","5":"5.75"},{"1":"406","2":"negative","3":"yes","4":"4.25","5":"4.50"},{"1":"407","2":"negative","3":"yes","4":"3.75","5":"3.25"},{"1":"408","2":"control","3":"no","4":"4.00","5":"4.50"},{"1":"409","2":"control","3":"no","4":"4.50","5":"5.00"},{"1":"410","2":"positive","3":"no","4":"5.00","5":"5.50"},{"1":"411","2":"control","3":"no","4":"4.25","5":"5.50"},{"1":"412","2":"negative","3":"no","4":"4.00","5":"2.00"},{"1":"413","2":"negative","3":"no","4":"4.25","5":"3.00"},{"1":"414","2":"positive","3":"yes","4":"5.00","5":"5.00"},{"1":"415","2":"positive","3":"no","4":"3.25","5":"4.50"},{"1":"416","2":"positive","3":"yes","4":"3.75","5":"5.25"},{"1":"417","2":"control","3":"no","4":"3.00","5":"2.50"},{"1":"418","2":"control","3":"yes","4":"4.50","5":"3.75"},{"1":"419","2":"negative","3":"yes","4":"5.50","5":"4.75"},{"1":"420","2":"control","3":"yes","4":"5.50","5":"3.25"},{"1":"421","2":"control","3":"no","4":"4.00","5":"4.50"},{"1":"422","2":"negative","3":"yes","4":"5.75","5":"7.00"},{"1":"423","2":"control","3":"no","4":"3.00","5":"3.25"},{"1":"424","2":"negative","3":"yes","4":"5.50","5":"5.00"},{"1":"425","2":"negative","3":"no","4":"6.25","5":"3.75"},{"1":"426","2":"negative","3":"yes","4":"1.50","5":"1.25"},{"1":"427","2":"positive","3":"no","4":"3.00","5":"1.25"},{"1":"428","2":"negative","3":"yes","4":"2.75","5":"1.00"},{"1":"429","2":"negative","3":"no","4":"3.75","5":"2.50"},{"1":"430","2":"negative","3":"yes","4":"6.25","5":"7.25"},{"1":"431","2":"control","3":"yes","4":"3.50","5":"3.25"},{"1":"432","2":"control","3":"yes","4":"5.50","5":"4.50"},{"1":"433","2":"positive","3":"yes","4":"3.50","5":"5.75"},{"1":"434","2":"negative","3":"no","4":"2.50","5":"1.00"},{"1":"435","2":"positive","3":"yes","4":"4.50","5":"4.75"},{"1":"436","2":"control","3":"yes","4":"4.50","5":"4.75"},{"1":"437","2":"control","3":"yes","4":"5.00","5":"4.25"},{"1":"438","2":"control","3":"yes","4":"3.00","5":"3.50"},{"1":"439","2":"control","3":"yes","4":"3.00","5":"3.00"},{"1":"440","2":"negative","3":"yes","4":"4.00","5":"2.50"},{"1":"441","2":"negative","3":"no","4":"4.75","5":"3.75"},{"1":"442","2":"negative","3":"yes","4":"4.75","5":"5.25"},{"1":"443","2":"control","3":"no","4":"3.00","5":"2.50"},{"1":"444","2":"negative","3":"no","4":"4.00","5":"4.00"},{"1":"445","2":"negative","3":"no","4":"4.25","5":"3.25"},{"1":"446","2":"control","3":"yes","4":"4.25","5":"2.25"},{"1":"447","2":"control","3":"yes","4":"5.00","5":"5.50"},{"1":"448","2":"positive","3":"yes","4":"4.75","5":"5.25"},{"1":"449","2":"negative","3":"no","4":"4.25","5":"3.00"},{"1":"450","2":"positive","3":"yes","4":"3.75","5":"5.25"},{"1":"451","2":"positive","3":"yes","4":"4.75","5":"4.25"},{"1":"452","2":"control","3":"no","4":"5.50","5":"5.75"},{"1":"453","2":"positive","3":"yes","4":"4.50","5":"2.75"},{"1":"454","2":"positive","3":"no","4":"3.50","5":"4.50"},{"1":"455","2":"negative","3":"yes","4":"3.25","5":"3.00"},{"1":"456","2":"positive","3":"no","4":"3.00","5":"2.75"},{"1":"457","2":"positive","3":"yes","4":"6.75","5":"7.00"},{"1":"458","2":"positive","3":"yes","4":"6.50","5":"6.75"},{"1":"459","2":"control","3":"no","4":"3.25","5":"4.50"},{"1":"460","2":"control","3":"yes","4":"4.50","5":"5.50"},{"1":"461","2":"positive","3":"no","4":"3.75","5":"4.00"},{"1":"462","2":"positive","3":"yes","4":"4.25","5":"3.25"},{"1":"463","2":"control","3":"yes","4":"3.75","5":"1.50"},{"1":"464","2":"negative","3":"yes","4":"3.50","5":"4.25"},{"1":"465","2":"negative","3":"yes","4":"5.50","5":"5.50"},{"1":"466","2":"positive","3":"yes","4":"4.75","5":"4.50"},{"1":"467","2":"control","3":"no","4":"4.50","5":"5.00"},{"1":"468","2":"negative","3":"yes","4":"3.50","5":"5.50"},{"1":"469","2":"control","3":"yes","4":"3.75","5":"5.25"},{"1":"470","2":"control","3":"yes","4":"5.50","5":"7.00"},{"1":"471","2":"control","3":"no","4":"4.00","5":"4.75"},{"1":"472","2":"control","3":"yes","4":"4.50","5":"4.50"},{"1":"473","2":"negative","3":"yes","4":"4.00","5":"4.00"},{"1":"474","2":"positive","3":"yes","4":"4.50","5":"5.75"},{"1":"475","2":"positive","3":"no","4":"5.75","5":"6.75"},{"1":"476","2":"control","3":"yes","4":"4.25","5":"4.75"},{"1":"477","2":"control","3":"no","4":"4.50","5":"2.25"},{"1":"478","2":"negative","3":"yes","4":"3.75","5":"3.75"},{"1":"479","2":"positive","3":"no","4":"4.25","5":"6.25"},{"1":"480","2":"control","3":"yes","4":"3.25","5":"2.00"},{"1":"481","2":"control","3":"no","4":"6.00","5":"7.25"},{"1":"482","2":"positive","3":"no","4":"4.75","5":"6.50"},{"1":"483","2":"positive","3":"yes","4":"3.25","5":"3.00"},{"1":"484","2":"positive","3":"yes","4":"3.25","5":"3.00"},{"1":"485","2":"negative","3":"yes","4":"4.00","5":"3.75"},{"1":"486","2":"positive","3":"no","4":"4.00","5":"3.50"},{"1":"487","2":"negative","3":"yes","4":"4.25","5":"5.50"},{"1":"488","2":"negative","3":"yes","4":"5.75","5":"5.50"},{"1":"489","2":"positive","3":"no","4":"4.50","5":"4.00"},{"1":"490","2":"positive","3":"yes","4":"3.00","5":"1.75"},{"1":"491","2":"positive","3":"no","4":"5.00","5":"4.50"},{"1":"492","2":"positive","3":"no","4":"3.50","5":"4.75"},{"1":"493","2":"positive","3":"yes","4":"4.25","5":"5.25"},{"1":"494","2":"negative","3":"yes","4":"5.00","5":"6.25"},{"1":"495","2":"positive","3":"yes","4":"3.00","5":"4.00"},{"1":"496","2":"negative","3":"no","4":"4.50","5":"4.00"},{"1":"497","2":"control","3":"no","4":"4.25","5":"4.75"},{"1":"498","2":"positive","3":"yes","4":"4.75","5":"5.50"},{"1":"499","2":"positive","3":"no","4":"4.75","5":"4.75"},{"1":"500","2":"negative","3":"yes","4":"3.50","5":"5.25"},{"1":"501","2":"control","3":"yes","4":"4.00","5":"4.75"},{"1":"502","2":"control","3":"no","4":"4.00","5":"3.25"},{"1":"503","2":"negative","3":"yes","4":"3.00","5":"3.75"},{"1":"504","2":"negative","3":"no","4":"5.25","5":"4.75"},{"1":"505","2":"positive","3":"no","4":"4.50","5":"4.00"},{"1":"506","2":"control","3":"yes","4":"5.00","5":"4.25"},{"1":"507","2":"positive","3":"no","4":"4.25","5":"4.25"},{"1":"508","2":"negative","3":"no","4":"4.25","5":"2.25"},{"1":"509","2":"control","3":"no","4":"3.50","5":"4.00"},{"1":"510","2":"control","3":"yes","4":"2.75","5":"3.50"},{"1":"511","2":"negative","3":"yes","4":"4.00","5":"4.00"},{"1":"512","2":"positive","3":"yes","4":"5.00","5":"5.75"},{"1":"513","2":"negative","3":"yes","4":"6.00","5":"5.75"},{"1":"514","2":"control","3":"yes","4":"4.00","5":"2.75"},{"1":"515","2":"control","3":"yes","4":"6.25","5":"6.25"},{"1":"516","2":"control","3":"yes","4":"6.25","5":"6.00"},{"1":"517","2":"negative","3":"yes","4":"3.50","5":"3.00"},{"1":"518","2":"control","3":"yes","4":"5.00","5":"4.00"},{"1":"519","2":"negative","3":"no","4":"4.25","5":"3.50"},{"1":"520","2":"control","3":"no","4":"6.00","5":"6.50"},{"1":"521","2":"positive","3":"no","4":"5.00","5":"4.75"},{"1":"522","2":"control","3":"no","4":"3.50","5":"1.25"},{"1":"523","2":"positive","3":"yes","4":"2.75","5":"2.75"},{"1":"524","2":"control","3":"no","4":"3.25","5":"3.75"},{"1":"525","2":"positive","3":"yes","4":"5.25","5":"6.50"},{"1":"526","2":"control","3":"yes","4":"3.75","5":"2.50"},{"1":"527","2":"positive","3":"yes","4":"5.25","5":"3.75"},{"1":"528","2":"control","3":"yes","4":"5.25","5":"4.75"},{"1":"529","2":"control","3":"yes","4":"6.25","5":"5.00"},{"1":"530","2":"control","3":"yes","4":"4.25","5":"4.00"},{"1":"531","2":"positive","3":"yes","4":"2.50","5":"2.75"},{"1":"532","2":"negative","3":"no","4":"3.75","5":"2.25"},{"1":"533","2":"control","3":"no","4":"5.25","5":"4.50"},{"1":"534","2":"control","3":"no","4":"3.50","5":"2.50"},{"1":"535","2":"control","3":"yes","4":"3.50","5":"1.75"},{"1":"536","2":"control","3":"yes","4":"5.50","5":"3.25"},{"1":"537","2":"control","3":"yes","4":"4.00","5":"5.00"},{"1":"538","2":"positive","3":"yes","4":"4.75","5":"4.50"},{"1":"539","2":"positive","3":"yes","4":"4.00","5":"4.50"},{"1":"540","2":"negative","3":"no","4":"5.50","5":"6.25"},{"1":"541","2":"control","3":"yes","4":"5.25","5":"3.75"},{"1":"542","2":"positive","3":"yes","4":"4.50","5":"4.50"},{"1":"543","2":"positive","3":"no","4":"5.00","5":"5.75"},{"1":"544","2":"control","3":"no","4":"2.75","5":"4.50"},{"1":"545","2":"negative","3":"yes","4":"3.50","5":"2.50"},{"1":"546","2":"negative","3":"no","4":"5.25","5":"3.75"},{"1":"547","2":"positive","3":"yes","4":"6.00","5":"7.00"},{"1":"548","2":"positive","3":"no","4":"4.00","5":"4.75"},{"1":"549","2":"control","3":"yes","4":"5.25","5":"5.00"},{"1":"550","2":"negative","3":"yes","4":"3.25","5":"3.75"},{"1":"551","2":"control","3":"no","4":"7.25","5":"7.75"},{"1":"552","2":"negative","3":"no","4":"3.50","5":"1.50"},{"1":"553","2":"negative","3":"yes","4":"7.50","5":"8.50"},{"1":"554","2":"positive","3":"yes","4":"2.75","5":"4.00"},{"1":"555","2":"positive","3":"yes","4":"2.75","5":"3.25"},{"1":"556","2":"negative","3":"no","4":"5.75","5":"6.00"},{"1":"557","2":"positive","3":"no","4":"1.75","5":"1.50"},{"1":"558","2":"positive","3":"no","4":"4.75","5":"6.00"},{"1":"559","2":"control","3":"no","4":"3.75","5":"3.25"},{"1":"560","2":"positive","3":"no","4":"3.75","5":"2.75"},{"1":"561","2":"negative","3":"yes","4":"4.25","5":"4.75"},{"1":"562","2":"positive","3":"no","4":"4.75","5":"4.75"},{"1":"563","2":"positive","3":"yes","4":"6.75","5":"7.75"},{"1":"564","2":"control","3":"no","4":"3.25","5":"3.50"},{"1":"565","2":"positive","3":"yes","4":"4.50","5":"4.50"},{"1":"566","2":"control","3":"yes","4":"5.00","5":"5.25"},{"1":"567","2":"negative","3":"yes","4":"3.25","5":"3.75"},{"1":"568","2":"control","3":"no","4":"3.00","5":"3.50"},{"1":"569","2":"positive","3":"yes","4":"5.25","5":"5.75"},{"1":"570","2":"negative","3":"yes","4":"5.50","5":"4.00"},{"1":"571","2":"positive","3":"no","4":"5.00","5":"3.75"},{"1":"572","2":"control","3":"no","4":"3.50","5":"3.75"},{"1":"573","2":"control","3":"no","4":"6.50","5":"7.50"},{"1":"574","2":"positive","3":"yes","4":"2.50","5":"2.75"},{"1":"575","2":"positive","3":"no","4":"5.00","5":"4.75"},{"1":"576","2":"control","3":"yes","4":"3.25","5":"3.50"},{"1":"577","2":"negative","3":"no","4":"3.75","5":"2.75"},{"1":"578","2":"negative","3":"no","4":"4.75","5":"3.25"},{"1":"579","2":"control","3":"no","4":"4.25","5":"5.00"},{"1":"580","2":"negative","3":"yes","4":"3.25","5":"3.25"},{"1":"581","2":"negative","3":"yes","4":"4.25","5":"4.50"},{"1":"582","2":"negative","3":"yes","4":"4.75","5":"3.00"},{"1":"583","2":"negative","3":"yes","4":"2.75","5":"1.00"},{"1":"584","2":"positive","3":"yes","4":"3.75","5":"3.00"},{"1":"585","2":"negative","3":"no","4":"4.00","5":"1.75"},{"1":"586","2":"control","3":"no","4":"3.00","5":"1.75"},{"1":"587","2":"positive","3":"no","4":"4.50","5":"5.50"},{"1":"588","2":"negative","3":"no","4":"6.00","5":"3.75"},{"1":"589","2":"negative","3":"no","4":"4.00","5":"3.50"},{"1":"590","2":"control","3":"yes","4":"3.00","5":"3.00"},{"1":"591","2":"negative","3":"no","4":"4.25","5":"3.75"},{"1":"592","2":"positive","3":"yes","4":"4.75","5":"6.75"},{"1":"593","2":"control","3":"yes","4":"2.75","5":"2.00"},{"1":"594","2":"positive","3":"no","4":"5.25","5":"6.00"},{"1":"595","2":"negative","3":"yes","4":"5.50","5":"6.75"},{"1":"596","2":"control","3":"yes","4":"5.00","5":"5.00"},{"1":"597","2":"positive","3":"no","4":"4.00","5":"3.50"},{"1":"598","2":"control","3":"no","4":"4.00","5":"2.75"},{"1":"599","2":"positive","3":"no","4":"4.50","5":"3.25"},{"1":"600","2":"negative","3":"yes","4":"4.50","5":"4.00"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<section id="one-way-anova-1" class="level2">
<h2 class="anchored" data-anchor-id="one-way-anova-1">One-way ANOVA</h2>
<p>In one-way ANOVA we compare the means of a dependent variable between two or more groups in a single independent variable. We can use this to test the main question of our experiment: whether the movie (<em>experimental_group</em>) has an effect on the trust in journalists (<em>trust_t2</em>).<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<p>We use the <code>aov_car</code> function from the <code>afex</code> package to fit the ANOVA model. The formula that we use in this function is, as usual, <code>dependent_variable ~ independent_variable</code>. However, we also need to specify the unique user id (<code>id</code>) using the <code>Error</code> function. This way we explicitly clarify that each row in the data belongs to a unique participant in the study, which prevents you from mixing up between-subjects and within-subjects effects (more on this in the <em>repeated measures</em> section) So the full formula is <code>dependent_variable ~ independent_variable + Error(id)</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">=</span> <span class="fu">aov_car</span>(trust_t2 <span class="sc">~</span> experiment_group <span class="sc">+</span> <span class="fu">Error</span>(id), <span class="at">data=</span>d)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>m</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type 3 tests)

Response: trust_t2
            Effect     df  MSE         F  ges p.value
1 experiment_group 2, 597 2.25 26.26 *** .081   &lt;.001
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '+' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>When we print the output of the <code>aov_car</code> function, we get the main results of the ANOVA test. In this one-way ANOVA we have a single independent variable, which is the <code>experiment_group</code>. The output shows us the results of the F-test (<span class="math inline">\(F_{2, 597} = 26.26, p &lt; 0.001\)</span>) which tells us that the difference between the groups is <strong>significant</strong>. In other words, the movie that participants watched had a significant effect on their trust in journalists.</p>
<p>We also get an <span class="math inline">\(eta^2\)</span> (eta squared) value in the <code>ges</code> column (generalized eta squared<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a>), This is a measure of <strong>effect size</strong> that tells us how much variance in the dependent variable is explained by the independent variable (similar to the <span class="math inline">\(R^2\)</span> value in regression).</p>
<div class="callout callout-style-default callout-note callout-titled" title="Comparing between groups">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Comparing between groups
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The <span class="math inline">\(eta^2\)</span> and F-test only tell us that there is a difference between the groups, but not <em>where</em> the difference is. To compare bewteen the groups, we can first of all look at their means. For this we’ll use the <code>emmeans</code> function from the <code>emmeans</code> package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>means <span class="ot">=</span> <span class="fu">emmeans</span>(m, <span class="st">"experiment_group"</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>means</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> experiment_group emmean    SE  df lower.CL upper.CL
 control            4.44 0.106 597     4.24     4.65
 negative           3.68 0.106 597     3.47     3.89
 positive           4.73 0.106 597     4.52     4.94

Confidence level used: 0.95 </code></pre>
</div>
</div>
<p>Now we can see that the lowest trust score is in the <em>negative</em> group, and the highest in the <em>positive</em> group. However, we do not yet know whether the diffences between all the groups are significant. It could be that the <em>positive</em> group is significantly higher than the <em>negative</em> group, but not significantly higher than the <em>control</em> group. To test this we can use the <code>pairs</code> function to get the pairwise comparisons for the means we just computed.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(means)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast            estimate   SE  df t.ratio p.value
 control - negative     0.765 0.15 597   5.095  &lt;.0001
 control - positive    -0.287 0.15 597  -1.915  0.1354
 negative - positive   -1.052 0.15 597  -7.010  &lt;.0001

P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
</div>
<p>Here we see all possible combinations of groups. The <strong>control - negative</strong> (control <em>minus</em> negative) row tells us how much the trust score in the control group is higher than in the negative group, and whether this difference is significant.</p>
<p>Finally, we can visualize the results. <code>afex</code> has a built-in plot function (afex_plot), but throughout this book we often use the flexible <code>plot_model</code> function from the <code>sjPlot</code> package, and we can use this here as well! We can get the linear model from the <code>aov_car</code> output using <code>$lm</code>, and then use the <code>plot_model</code> function to visualize the results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(m<span class="sc">$</span>lm, <span class="at">type=</span><span class="st">'pred'</span>, <span class="at">terms=</span><span class="st">'experiment_group'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
Unable to calculate text width/height (using zero)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
Unable to calculate text width/height (using zero)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
Unable to calculate text width/height (using zero)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
Unable to calculate text width/height (using zero)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
Unable to calculate text width/height (using zero)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
Unable to calculate text width/height (using zero)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
Unable to calculate text width/height (using zero)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"
Warning in grid.Call(C_stringMetric, as.graphicsAnnot(x$label)): no font could
be found for family "Arial"</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
Unable to calculate text width/height (using zero)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
Unable to calculate text width/height (using zero)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
Unable to calculate text width/height (using zero)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="anova_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<section id="experimental-versus-observed-factors" class="level3">
<h3 class="anchored" data-anchor-id="experimental-versus-observed-factors"><em>Experimental</em> versus <em>observed</em> factors</h3>
<p>In the previous example our independent variable was <em>experimentally manipulated</em>: we randomly assigned participants to the three groups. Accordingly, any effects that we find are likely to represent causal relationships. If people with different opinions about journalism were randomly distributed over the groups, we can be confident that the differences we find after showing them different movies are due to the movies themselves.</p>
<p>However, in some cases we might have an independent variable that is <em>observed</em>, meaning that we did not manipulate it, but only <em>observed</em> a value that was already there. This is the case for variables like <em>age</em> and <em>gender</em>, and in our case also for <em>np_subscribed</em> (whether participants have a newspaper subscription).</p>
<p>When factors are observed, it has two implications for the ANOVA test:</p>
<ul>
<li><strong>Causality</strong>. It limits the ability to make causal inferences about the effect of the independent variable on the dependent variable.</li>
<li><strong>Effect size</strong>. We need to correct the <span class="math inline">\(eta^2\)</span> value to get more reliable effect sizes. The <code>afex</code> package does this automatically for us by using the generalized <span class="math inline">\(eta^2\)</span> value (<code>ges</code> column in the output).However, we do need to tell it when a factor is observed, using the <code>observed</code> argument in the <code>aov_car</code> function.</li>
</ul>
<p>Let’s see how this works in practice, using the <code>np_subscription</code> variable as an observed factor. With <code>observed='np_subscription'</code> we tell the <code>aov_car</code> function that the <code>np_subscription</code> variable is an observed factor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aov_car</span>(trust_t2 <span class="sc">~</span> np_subscription <span class="sc">+</span> <span class="fu">Error</span>(id), <span class="at">observed=</span><span class="st">'np_subscription'</span>, <span class="at">data=</span>d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Anova Table (Type 3 tests)

Response: trust_t2
           Effect     df  MSE         F  ges p.value
1 np_subscription 1, 598 2.33 30.43 *** .048   &lt;.001
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '+' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>In this case our results only tell us that there is a significant difference between people with and without a newspaper subscription. We cannot conclude that this is because having a newspaper subscription causes people to trust journalists more. We are no longer certain about the order of the effect (trust in journalists might also cause people to get a newspaper subscription), and there can be confounding variables that influence both (e.g., education level, socio-economic status).</p>
</section>
</section>
<section id="two-way-anova-1" class="level2">
<h2 class="anchored" data-anchor-id="two-way-anova-1">Two-way ANOVA</h2>
<p>In a two-way ANOVA we compare the means of a dependent variable between two or more groups in two independent variables. To demonstrate this we’ll use the <code>np_subscription</code> variable as a second independent variable.</p>
<p>The formula for a two-way ANOVA is <code>dependent_variable ~ independent_variable_1*independent_variable_2 + Error(id)</code>. The <code>*</code> symbol is a shorthand for including both the main effects and the interaction effect between the two independent variables. Note that we also again specify that <code>np_subscription</code> is an observed factor.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">=</span> <span class="fu">aov_car</span>(trust_t2 <span class="sc">~</span> experiment_group<span class="sc">*</span>np_subscription <span class="sc">+</span> <span class="fu">Error</span>(id), </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">observed=</span><span class="st">'np_subscription'</span>, <span class="at">data=</span>d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now our output shows three F-tests: one for the main effect of <code>experiment_group</code>, one for the main effect of <code>np_subscription</code>, and one for the interaction effect between the two. We also get three <span class="math inline">\(eta^2\)</span> values, one for each effect, which tell us how much variance is explained by each effect.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Comparing between groups">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Comparing between groups
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We can again use the <code>emmeans</code> function to get the means for each group. Let’s visualize the results first to get a better idea of how the two independent variables interact to affect the trust in journalists.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(m<span class="sc">$</span>lm, <span class="at">type=</span><span class="st">'pred'</span>, <span class="at">terms=</span><span class="fu">c</span>(<span class="st">'experiment_group'</span>, <span class="st">'np_subscription'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
Unable to calculate text width/height (using zero)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
Unable to calculate text width/height (using zero)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
Unable to calculate text width/height (using zero)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
Unable to calculate text width/height (using zero)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
Unable to calculate text width/height (using zero)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
Unable to calculate text width/height (using zero)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
Unable to calculate text width/height (using zero)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
Unable to calculate text width/height (using zero)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
Unable to calculate text width/height (using zero)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
Unable to calculate text width/height (using zero)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
Unable to calculate text width/height (using zero)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
Unable to calculate text width/height (using zero)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
Unable to calculate text width/height (using zero)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
Unable to calculate text width/height (using zero)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
Unable to calculate text width/height (using zero)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
Unable to calculate text width/height (using zero)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
Unable to calculate text width/height (using zero)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, :
Unable to calculate text width/height (using zero)</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"
Warning in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y, : no
font could be found for family "Arial"</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="anova_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Here we see that the effect of <code>np_subscription</code> (having a newspaper subscription) mostly matters for the <em>negative</em> group. It seems that overall people that watched a <em>negative</em> movie have a lower trust in journalists, but this is mostly true for people that do not have a newspaper subscription. In other words, people that have a newspaper subscription might not be as affected by the negative movie.</p>
<p>We can now use the <code>emmeans</code> function to test these differences. To see how the effect of <code>experimental_group</code> is different for people that do or do not have a newspaper subscription, we can look at means of the <code>experiment_group</code> variable <strong>conditional on</strong> (<code>by</code>) the <code>np_subscription</code> variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>means <span class="ot">=</span> <span class="fu">emmeans</span>(m, <span class="st">'experiment_group'</span>, <span class="at">by=</span><span class="st">'np_subscription'</span>)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>means</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>np_subscription = no:
 experiment_group emmean    SE  df lower.CL upper.CL
 control            4.09 0.160 594     3.78     4.41
 negative           2.88 0.151 594     2.59     3.18
 positive           4.71 0.150 594     4.42     5.01

np_subscription = yes:
 experiment_group emmean    SE  df lower.CL upper.CL
 control            4.68 0.132 594     4.42     4.94
 negative           4.33 0.137 594     4.06     4.60
 positive           4.75 0.138 594     4.48     5.02

Confidence level used: 0.95 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(means)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>np_subscription = no:
 contrast            estimate    SE  df t.ratio p.value
 control - negative    1.2093 0.220 594   5.497  &lt;.0001
 control - positive   -0.6194 0.219 594  -2.830  0.0133
 negative - positive  -1.8286 0.213 594  -8.587  &lt;.0001

np_subscription = yes:
 contrast            estimate    SE  df t.ratio p.value
 control - negative    0.3532 0.190 594   1.859  0.1516
 control - positive   -0.0649 0.191 594  -0.340  0.9383
 negative - positive  -0.4181 0.195 594  -2.149  0.0811

P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
</div>
<p>We can now compare how the movie affects the trust in journalists, while taking into account how this is conditional on whether people have a newspaper subscription.</p>
<p>Likewise, we could also compare how the newspaper subscription affects the trust in journalists, while taking into account how this is conditional on the movie that people watched.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>means <span class="ot">=</span> <span class="fu">emmeans</span>(m, <span class="st">'np_subscription'</span>, <span class="at">by=</span><span class="st">'experiment_group'</span>)</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>means</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(means)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And finally, we could also compare between ALL the groups.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>means <span class="ot">=</span> <span class="fu">emmeans</span>(m, <span class="fu">c</span>(<span class="st">'experiment_group'</span>, <span class="st">'np_subscription'</span>))</span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>means</span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(means)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
</div>
</section>
</section>
<section id="conditions-and-assumptions" class="level1">
<h1>Conditions and assumptions</h1>
<p>ANOVA is a parametric test, which means that it makes assumptions about the data. If these assumptions are violated, the results of the ANOVA can be unreliable. The most important assumptions are:</p>
<ol type="1">
<li><strong>Normality</strong>. The dependent variable should be normally distributed in each group.</li>
<li><strong>Homogeneity of variance</strong>. The variance of the dependent variable should (approximately) be equal in each group.</li>
<li><strong>Independence</strong>. Observations should be independent of each other.</li>
</ol>
<p>Here we will only discuss the assumption of <strong>homogeneity of variance</strong>, because it is more specific to ANOVA. For the other assumptions, which are more general to linear models, we refer to the <a href="../../analysis/tests/linear-regression.html">regression tutorial</a>. If you have not yet learned about regression, you can ignore the details of these other assumptions for now.</p>
<section id="homogeneity-of-variance" class="level3">
<h3 class="anchored" data-anchor-id="homogeneity-of-variance">Homogeneity of variance</h3>
<p>Homogeneity of variance means that the variance of the dependent variable should be (approximately) equal in each group. In our one-way ANOVA example, this means that the variance of the trust score should be equal in the <em>control</em>, <em>positive</em>, and <em>negative</em> groups.</p>
<p>We can test this with the Levene’s test, which is a test for homogeneity of variance. The null hypothesis of the Levene’s test is that the variance is equal in each group. If the p-value of the test is less than 0.05, we reject the null hypothesis and conclude that the variance is not equal in each group.</p>
<p>To perform the Levene’s test we can use the <code>leveneTest</code> function from the <code>car</code> package. To test whether the variance of the trust score (dependent variable) is equal in each group of the independent variable, we use the formula <code>dependent_variable ~ independent_variable</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(trust_t2 <span class="sc">~</span> experiment_group, <span class="at">data=</span>d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Df"],"name":[1],"type":["int"],"align":["right"]},{"label":["F value"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Pr(>F)"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"2","2":"0.8322031","3":"0.4355938","_rn_":"group"},{"1":"597","2":"NA","3":"NA","_rn_":""}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>In this case the Levene’s test is not significant, which means that we can assume that the variance of the trust score is sufficiently equal in each group.</p>
<p>For two-way anova, we can also perform the Levene’s test for each combination of the two independent variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(trust_t2 <span class="sc">~</span> experiment_group<span class="sc">*</span>np_subscription, <span class="at">data=</span>d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["Df"],"name":[1],"type":["int"],"align":["right"]},{"label":["F value"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["Pr(>F)"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"5","2":"0.6001174","3":"0.6998962","_rn_":"group"},{"1":"594","2":"NA","3":"NA","_rn_":""}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<section id="what-if-the-variance-is-not-equal" class="level4">
<h4 class="anchored" data-anchor-id="what-if-the-variance-is-not-equal">What if the variance is not equal?</h4>
<p>If Levene’s test is significant, we would need to look more carefully into the variance across groups. ANOVA is fairly robust to violations of the assumption of homogeneity of variance, but if the variance is very different between groups, the results of the ANOVA can be unreliable.</p>
<p>So how much difference in variance is too much? One strategy is to look at the ratio of the largest to the smallest variance across the groups. A common rule of thumb is that this ratio should not be more than 3.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> However, note that this is just a rule of thumb, and if the sample size is small (less than 30 per group), or the groups are very unbalanced (i.e.&nbsp;one group has much more observations than the others), it is better to be more conservative.</p>
<p>In any case, it is always a good starting point to look at the sample size and variances across groups to see where potential problems might be.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>vars <span class="ot">=</span> d <span class="sc">|&gt;</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(experiment_group, np_subscription) <span class="sc">|&gt;</span></span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">n =</span> <span class="fu">n</span>(), <span class="at">variance =</span> <span class="fu">var</span>(trust_t2)) </span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a>vars</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["experiment_group"],"name":[1],"type":["fct"],"align":["left"]},{"label":["np_subscription"],"name":[2],"type":["fct"],"align":["left"]},{"label":["n"],"name":[3],"type":["int"],"align":["right"]},{"label":["variance"],"name":[4],"type":["dbl"],"align":["right"]}],"data":[{"1":"control","2":"no","3":"81","4":"2.249132"},{"1":"control","2":"yes","3":"119","4":"1.893747"},{"1":"negative","2":"no","3":"90","4":"1.761517"},{"1":"negative","2":"yes","3":"110","4":"2.154738"},{"1":"positive","2":"no","3":"92","4":"1.987548"},{"1":"positive","2":"yes","3":"108","4":"2.332354"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="do">## ratio of largest to smallest variance</span></span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(vars<span class="sc">$</span>variance) <span class="sc">/</span> <span class="fu">min</span>(vars<span class="sc">$</span>variance)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.32406</code></pre>
</div>
</div>
<p>In this case we have quite a lot of observations in each group, so if the ratio of the largest to the smallest variance (<span class="math inline">\(S_{max}^2 / S_{min}^2 = 2.33 / 1.76 =  1.32\)</span>)<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a> is less than 3, we can assume that the variance is sufficiently equal in each group (and we already know that the Levene’s test is not significant).</p>
<p>But what if the homogeneity of variance assumption <em>is</em> violated? One option would be to use a different model, like ANOVA with Welch’s correction, or a non-parametric test like the Kruskal-Wallis test. But perhaps more importantly, if you do find such strong differences in variance, you should look more closely at the data and think about what might be causing these differences. Why is the variance higher in one group than in the other? Is there perhaps a confounding variable or moderator that you have not yet taken into account? Perhaps an experimental treatment was not applied correctly, or it might only have an effect in a specific subgroup of participants.</p>
<p>Most importantly, do not think of testing these assumptions as a <em>hurdle</em> that you need to pass before you can use ANOVA. At the end of the day, the purpose of statistics is to help us better understand our data. If you find that your data does not meet the assumptions of ANOVA, this is not a failure, but an observation in itself that might warrant exploration. When in doubt, you can still use ANOVA, as long as you’re transparent about the assumptions that are violated, and exert caution in your interpretation of the results.</p>



</section>
</section>
</section>


<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a><div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-dean00" class="csl-entry" role="listitem">
Dean, Angela, and Daniel Voss. 1999. <em>Design and Analysis of Experiments</em>. Springer.
</div>
<div id="ref-olejnik03" class="csl-entry" role="listitem">
Olejnik, Stephen, and James Algina. 2003. <span>“Generalized Eta and Omega Squared Statistics: Measures of Effect Size for Some Common Research Designs.”</span> <em>Psychological Methods</em> 8 (4): 434.
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>It is also possible to use ANOVA with non-experimental (i.e.&nbsp;observational) data. However, this limits our ability to make causal inferences. For observational data it is more common to use <a href="../../analysis/tests/linear-regression.html">regression analysis</a>, because this provides more flexibility to control for confounding variables. (This is also possible with more advanced forms of ANOVA, like ANCOVA and MANOVA).<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>This is similar to an independent samples t-test, but can be used for more than two groups.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>This is similar to a paired samples t-test, but can be used for more than two groups. This is primarily used for within-subjects designs, where the same participants are measured multiple times.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>We’re using the trust score <em>after</em> watching the movie. It is <em>ok</em> to ignore the trust score before watching the movie, because we’ve randomly assigned participants to the different groups. This means that the trust score before watching the movie should be the same in each group. However, as we’ll show below, we could also use a repeated measures ANOVA to compare the trust score before and after watching the movie.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>The generalized <span class="math inline">\(eta2\)</span> is a generalization of the (partial) <span class="math inline">\(eta2\)</span> value that is often reported in ANOVA output. It was proposed by <span class="citation" data-cites="olejnik03">Olejnik and Algina (<a href="#ref-olejnik03" role="doc-biblioref">2003</a>)</span> because regular partial <span class="math inline">\(eta2\)</span> values can be misleading when comparing between studies with different designs. Specifically, it allows taking into account whether factors in the model are <em>experimentally manipulated</em> or <em>observed</em>. In the <strong>When factors are observed</strong> subsection below we show how to specify this in the <code>aov_car</code> function.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>By ‘rule of thumb’, we mean that it’s a general guideline, and not a number that is set in stone. Different authors have also proposed different values for this ratio. One source for the 3:1 ratio is <span class="citation" data-cites="dean00">Dean and Voss (<a href="#ref-dean00" role="doc-biblioref">1999</a>)</span>. There is also Hartley’s Fmax test, which is a more formal test that looks at the ratio of the largest to the smallest variance, and can take sample size and number of groups into account. However, this test is in turn sensitive to normal distribution of data, and requires groups to be balanced. Ultimately, there is no simple solution answer to the question “how much difference in variance is too much?”.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>The <span class="math inline">\(S_{max}^2\)</span> and <span class="math inline">\(S_{min}^2\)</span> are the largest and smallest variance across the groups, which you can look up in the data frame above. Note that <span class="math inline">\(S^2\)</span> is just the mathematical notation for variance (<span class="math inline">\(S\)</span> is the standard deviation, so <span class="math inline">\(S^2\)</span> is the variance).<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../analysis/tests/linear-regression.html" class="pagination-link" aria-label="Linear regression">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Linear regression</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../good-to-know/function-documentation.html" class="pagination-link" aria-label="Function Documentation">
        <span class="nav-page-text">Function Documentation</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>